//! `<crossPath>`: a path for pedestrians across a junction's roads.
//!
//! `tests/data/cross_paths.xodr` is generated by `cross_paths.py`.

use libopendrive::{
    load_file_with_provenance, CrossPath, CrossPathEnd, LaneId, Provenance, Warning,
};

const FIXTURE: &str = "tests/data/cross_paths.xodr";

fn lane(prov: &Provenance, road: &str, od_id: i32) -> LaneId {
    prov.lanes
        .iter()
        .find(|p| p.road_id == road && p.od_id == od_id)
        .unwrap()
        .lane
}

#[test]
fn a_cross_path_joins_a_lane_part_way_along_it_to_the_crossing_road_and_on() {
    let (net, prov) = load_file_with_provenance(FIXTURE).unwrap();
    let crossing = lane(&prov, "20", -1);
    assert_eq!(
        net.cross_paths(),
        [CrossPath {
            crossing: net.road_by_od_id("20").unwrap().id(),
            start: CrossPathEnd {
                lane: lane(&prov, "1", 2),
                s: 25.0,
                crossing_lane: crossing,
            },
            end: CrossPathEnd {
                lane: lane(&prov, "1", -2),
                s: 25.0,
                crossing_lane: crossing,
            },
        }]
    );
    assert_eq!(prov.cross_paths.len(), 1);
    assert_eq!(
        (
            prov.cross_paths[0].junction_id.as_str(),
            prov.cross_paths[0].od_id.as_str()
        ),
        ("5", "0")
    );
}

#[test]
fn a_cross_path_off_the_end_of_its_road_is_dropped_with_a_warning() {
    let (_, prov) = load_file_with_provenance(FIXTURE).unwrap();
    let dropped: Vec<_> = prov
        .warnings
        .iter()
        .filter(|w| matches!(w, Warning::CrossPathDropped { .. }))
        .collect();
    assert_eq!(
        dropped,
        [&Warning::CrossPathDropped {
            junction_id: "5".into(),
            cross_path_id: "1".into(),
            road_id: "20".into(),
        }]
    );
    assert_eq!(
        dropped[0].to_string(),
        "junction \"5\": <crossPath> \"1\" on road \"20\" dropped"
    );
}
