//! `<crossSectionSurface>`: a road's surface across it, as strips.
//!
//! `tests/data/cross_sections.xodr` is generated by `cross_sections.py`.

use libopendrive::{load_file_with_provenance, RoadNetwork, RoadPosition, Warning};

const FIXTURE: &str = "tests/data/cross_sections.xodr";

fn z(net: &RoadNetwork, s: f64, t: f64) -> f64 {
    let road = net.road_by_od_id("0").unwrap().id();
    f64::from(net.road_point(RoadPosition { road, s, t }).unwrap().z)
}

fn close(got: f64, want: f64) {
    assert!((got - want).abs() < 1e-5, "{got} != {want}");
}

#[test]
fn each_lane_border_stands_on_the_strip_under_it() {
    let (net, _) = load_file_with_provenance(FIXTURE).unwrap();
    // Left of the 0.5 m offset, the inner strip falls 2 %: at t = 3, 2.5 m
    // across it.
    close(z(&net, 10.0, 3.0), -0.05);
    // Past its 3 m, the relative outer strip stands on its edge, -0.06, and
    // rises 5 %: at t = 6, 2.5 m across.
    close(z(&net, 10.0, 6.0), -0.06 + 0.125);
    // On the right, the one strip reaches to the edge: 0.1 m, plus 1 mm a
    // metre along the road, rising 2 % to the left, -3.5 m and -6.5 m across.
    close(z(&net, 10.0, -3.0), 0.11 - 0.07);
    close(z(&net, 10.0, -6.0), 0.11 - 0.13);
    close(z(&net, 40.0, -6.0), 0.14 - 0.13);
}

#[test]
fn a_lane_goes_straight_across_between_its_borders() {
    let (net, _) = load_file_with_provenance(FIXTURE).unwrap();
    // Lane -1 runs from t = 0, on the right strip 0.5 m from the offset, to
    // t = -3.
    let (inner, outer) = (0.11 - 0.01, 0.11 - 0.07);
    close(z(&net, 10.0, -1.5), (inner + outer) / 2.0);
}

#[test]
fn the_crate_warns_of_a_surface_with_superelevation_and_a_mode_it_does_not_know() {
    let (_, prov) = load_file_with_provenance(FIXTURE).unwrap();
    let on_1: Vec<String> = prov
        .warnings
        .iter()
        .filter(|w| w.road_id() == "1")
        .map(|w| w.to_string())
        .collect();
    assert_eq!(
        on_1,
        [
            "road \"1\": <strip> 2 has mode \"sideways\", read as independent",
            "road \"1\": <crossSectionSurface> with <shape>s or a <superelevation>, heights added",
        ]
    );
    assert!(prov
        .warnings
        .iter()
        .any(|w| matches!(w, Warning::CrossSectionWithShape { .. })));
}

#[test]
fn the_surface_mesh_stays_closed() {
    let (net, _) = load_file_with_provenance(FIXTURE).unwrap();
    net.surface_mesh().validate().unwrap();
}
