//! Direct junctions: `<junction type="direct">`, whose connections join
//! roads end to end through a `linkedRoad`.
//!
//! `tests/data/direct_junctions.xodr` is generated by `direct_junctions.py`.
//! Road 0 splits into roads 1 and 2 through direct junction 8, which gives
//! its connections one way only. Roads 3 and 4 meet through direct junction
//! 9, which gives them both ways.

use xodr::{load_file_with_provenance, Lane, Provenance, RoadNetwork, Warning};

const FIXTURE: &str = "tests/data/direct_junctions.xodr";

fn fixture() -> (RoadNetwork, Provenance) {
    load_file_with_provenance(FIXTURE).expect("the fixture loads")
}

/// The baked lane `od_id` on road `road`.
fn lane<'a>(net: &'a RoadNetwork, prov: &Provenance, road: &str, od_id: i32) -> &'a Lane {
    let p = prov
        .lanes
        .iter()
        .find(|p| p.road_id == road && p.od_id == od_id)
        .unwrap_or_else(|| panic!("road {road} lane {od_id}"));
    net.lane(p.lane).expect("a baked lane")
}

#[test]
fn a_direct_junction_links_the_incoming_lanes_into_the_linked_road() {
    let (net, prov) = fixture();
    let l = |road, id| lane(&net, &prov, road, id);
    assert_eq!(l("0", -1).successors, vec![l("1", -1).id]);
    assert_eq!(l("0", -2).successors, vec![l("2", -1).id]);
    assert_eq!(l("1", -1).predecessors, vec![l("0", -1).id]);
    assert_eq!(l("2", -1).predecessors, vec![l("0", -2).id]);
}

#[test]
fn a_direct_junction_links_the_linked_road_back_into_the_incoming_one() {
    let (net, prov) = fixture();
    let l = |road, id| lane(&net, &prov, road, id);
    assert_eq!(l("1", 1).successors, vec![l("0", 1).id]);
    assert_eq!(l("0", 1).predecessors, vec![l("1", 1).id]);
}

#[test]
fn a_direct_junction_given_both_ways_links_each_lane_once() {
    let (net, prov) = fixture();
    let l = |road, id| lane(&net, &prov, road, id);
    assert_eq!(l("3", -1).successors, vec![l("4", -1).id]);
    assert_eq!(l("4", 1).successors, vec![l("3", 1).id]);
    assert_eq!(l("3", 1).predecessors, vec![l("4", 1).id]);
}

#[test]
fn a_connection_without_the_road_it_leads_into_is_dropped_with_a_warning() {
    let (_, prov) = fixture();
    assert_eq!(
        prov.warnings,
        vec![
            Warning::ConnectionDropped {
                incoming_road_id: "0".into(),
                junction_id: "8".into(),
                connection_id: "2".into(),
            },
            Warning::ConnectionDropped {
                incoming_road_id: "3".into(),
                junction_id: "10".into(),
                connection_id: "0".into(),
            },
        ]
    );
}
