//! Junction `<boundary>` and `<elevationGrid>`: the area of a junction and
//! the height of its ground.
//!
//! `tests/data/junction_areas.xodr` is generated by `junction_areas.py`.

use libopendrive::{load_file_with_provenance, JunctionArea, Warning};

const FIXTURE: &str = "tests/data/junction_areas.xodr";

fn areas() -> (Vec<JunctionArea>, Vec<Warning>) {
    let (net, prov) = load_file_with_provenance(FIXTURE).unwrap();
    (net.junction_areas().to_vec(), prov.warnings)
}

/// Twice the area a ring encloses in plan, positive counter-clockwise.
fn area(ring: &[libopendrive::Point]) -> f32 {
    ring.iter()
        .zip(ring.iter().cycle().skip(1))
        .map(|(a, b)| a.x * b.y - b.x * a.y)
        .sum::<f32>()
        / 2.0
}

#[test]
fn a_boundary_runs_counter_clockwise_round_its_segments_on_the_road_surface() {
    let (areas, _) = areas();
    let seven = &areas[0];
    assert_eq!(seven.od_id, "7");
    assert!(
        (area(&seven.boundary) - 70.0).abs() < 1e-3,
        "{}",
        area(&seven.boundary)
    );
    let corners = [(20.0, -3.5), (30.0, -3.5), (30.0, 3.5), (20.0, 3.5)];
    for (x, y) in corners {
        assert!(
            seven
                .boundary
                .iter()
                .any(|p| (p.x - x).abs() < 1e-4 && (p.y - y).abs() < 1e-4 && p.z.abs() < 1e-6),
            "no corner at ({x}, {y})"
        );
    }
}

#[test]
fn the_grid_gives_its_heights_at_its_points_and_between_them() {
    let (areas, _) = areas();
    let seven = &areas[0];
    let at = |x, y| seven.height_at(x, y).unwrap();
    assert!((at(22.0, 0.0) - 0.2).abs() < 1e-9);
    assert!((at(26.0, 4.0)).abs() < 1e-9);
    // The cubic through the line's heights 0, 0.2, 0.2 and 0 rises between
    // the two middle ones: to 0.225 halfway, with slopes of 0.1 and -0.1.
    assert!((at(24.0, 0.0) - 0.225).abs() < 1e-9);
    let between = at(20.0, 0.0);
    assert!(between > 0.0 && between < 0.2, "{between}");
    assert!(seven.height_at(31.0, 0.0).is_none());
    assert!(seven.height_at(24.0, 4.5).is_none());
}

#[test]
fn the_mesh_covers_the_boundary_at_the_grids_height() {
    let (areas, _) = areas();
    let mesh = areas[0].mesh();
    mesh.validate().unwrap();
    let covered: f32 = mesh
        .indices
        .chunks_exact(3)
        .map(|t| {
            let [a, b, c] = [0, 1, 2].map(|k| mesh.vertices[t[k] as usize]);
            ((b.x - a.x) * (c.y - a.y) - (b.y - a.y) * (c.x - a.x)) / 2.0
        })
        .sum();
    assert!((covered - 70.0).abs() < 1e-2, "{covered}");
    let top = mesh.vertices.iter().map(|v| v.z).fold(0.0_f32, f32::max);
    assert!(top > 0.2 && top <= 0.225 + 1e-6, "{top}");
    assert!(mesh.normals.iter().all(|n| n.z > 0.9));
}

#[test]
fn the_crate_warns_that_the_grid_leaves_the_roads_as_they_are() {
    let (_, warnings) = areas();
    assert!(warnings.contains(&Warning::ElevationGridNotApplied {
        junction_id: "7".into()
    }));
}

#[test]
fn a_clockwise_boundary_with_a_segment_it_cannot_place_is_turned_and_warned_of() {
    let (areas, warnings) = areas();
    let eight = &areas[1];
    assert_eq!(eight.od_id, "8");
    assert!(area(&eight.boundary) > 0.0);
    assert!(eight.grid.is_none());
    let about_eight: Vec<String> = warnings
        .iter()
        .filter(|w| w.to_string().contains("junction \"8\""))
        .map(|w| w.to_string())
        .collect();
    assert_eq!(
        about_eight,
        [
            "junction \"8\": <boundary> segment on road \"99\" dropped",
            "junction \"8\": <boundary> segments leave a 10.00 m gap, joined straight",
            "junction \"8\": <boundary> runs clockwise, turned round",
        ]
    );
    let dropped = warnings
        .iter()
        .find(|w| matches!(w, Warning::BoundarySegmentDropped { .. }))
        .unwrap();
    assert_eq!(dropped.road_id(), "99");
}
