//! Junction `<priority>`: which road of a junction gives way to which.
//!
//! `tests/data/junction_priority.xodr` is generated by
//! `junction_priority.py`.

use libopendrive::{load_file_with_provenance, Priority, RoadId, RoadNetwork, Warning};

const FIXTURE: &str = "tests/data/junction_priority.xodr";

fn road(net: &RoadNetwork, od_id: &str) -> RoadId {
    net.road_by_od_id(od_id).unwrap().id()
}

#[test]
fn a_priority_names_the_road_with_it_and_the_road_that_gives_way() {
    let (net, prov) = load_file_with_provenance(FIXTURE).unwrap();
    let (high, low) = (road(&net, "10"), road(&net, "11"));
    assert_eq!(net.priorities(), [Priority { high, low }]);
    assert_eq!(prov.priorities.len(), 1);
    assert_eq!(prov.priorities[0].junction_id, "5");
    assert_eq!(net.yields_to(low).collect::<Vec<_>>(), [high]);
    assert_eq!(net.yields_to(high).count(), 0);
}

#[test]
fn a_priority_naming_a_road_the_load_lacks_is_dropped_with_a_warning() {
    let (_, prov) = load_file_with_provenance(FIXTURE).unwrap();
    let dropped: Vec<_> = prov
        .warnings
        .iter()
        .filter(|w| matches!(w, Warning::PriorityDropped { .. }))
        .collect();
    assert_eq!(
        dropped,
        [&Warning::PriorityDropped {
            junction_id: "5".into(),
            high: "99".into(),
            low: "11".into(),
        }]
    );
    assert_eq!(dropped[0].road_id(), "11");
    assert_eq!(
        dropped[0].to_string(),
        "junction \"5\": <priority> of road \"99\" over road \"11\" dropped, the load has no such road"
    );
}

#[cfg(feature = "serde")]
#[test]
fn priorities_survive_a_serde_round_trip() {
    let (net, _) = load_file_with_provenance(FIXTURE).unwrap();
    let back: RoadNetwork = serde_json::from_str(&serde_json::to_string(&net).unwrap()).unwrap();
    assert_eq!(back.priorities(), net.priorities());
}
