//! A common junction's incoming road whose `<link>` leaves the junction out.
//!
//! `tests/data/junction_links.xodr` is generated by `junction_links.py`.

use libopendrive::{
    load_file_with_provenance, load_str_with_provenance, LaneId, Provenance, RoadEnd, Warning,
};

const FIXTURE: &str = "tests/data/junction_links.xodr";

fn lane(prov: &Provenance, road: &str, od_id: i32) -> LaneId {
    prov.lanes
        .iter()
        .find(|p| p.road_id == road && p.od_id == od_id)
        .unwrap_or_else(|| panic!("road {road} lane {od_id}"))
        .lane
}

#[test]
fn a_road_that_leaves_out_its_junction_drives_into_it_from_the_end_its_connecting_road_names() {
    let (net, prov) = load_file_with_provenance(FIXTURE).unwrap();
    let into = net.lane(lane(&prov, "1", -1)).unwrap();
    assert_eq!(into.successors, [lane(&prov, "10", -1)]);
    let out = net.lane(lane(&prov, "10", -1)).unwrap();
    assert_eq!(out.predecessors, [lane(&prov, "1", -1)]);
    assert_eq!(out.successors, [lane(&prov, "2", -1)]);
}

#[test]
fn the_crate_warns_that_the_link_is_missing() {
    let (_, prov) = load_file_with_provenance(FIXTURE).unwrap();
    let missing: Vec<_> = prov
        .warnings
        .iter()
        .filter(|w| matches!(w, Warning::JunctionLinkMissing { .. }))
        .collect();
    assert_eq!(
        missing,
        [&Warning::JunctionLinkMissing {
            road_id: "1".into(),
            junction_id: "5".into(),
            end: RoadEnd::End,
        }]
    );
    assert_eq!(
        missing[0].to_string(),
        "road \"1\": its <link> leaves out junction \"5\" at its end, linked from the junction's connecting road"
    );
    assert_eq!(missing[0].road_id(), "1");
}

#[test]
fn a_road_whose_connecting_road_does_not_name_it_stays_unlinked() {
    let (net, prov) = load_file_with_provenance(FIXTURE).unwrap();
    assert!(net
        .lane(lane(&prov, "3", -1))
        .unwrap()
        .successors
        .is_empty());
    assert!(!prov.warnings.iter().any(|w| w.road_id() == "3"));
}

#[test]
fn a_connecting_road_that_names_no_contact_point_leaves_the_road_unlinked() {
    let xml = std::fs::read_to_string(FIXTURE).unwrap().replace(
        r#"<predecessor elementType="road" elementId="1" contactPoint="end"/>"#,
        r#"<predecessor elementType="road" elementId="1"/>"#,
    );
    let (net, prov) = load_str_with_provenance(&xml).unwrap();
    assert!(net
        .lane(lane(&prov, "1", -1))
        .unwrap()
        .successors
        .is_empty());
    assert!(!prov
        .warnings
        .iter()
        .any(|w| matches!(w, Warning::JunctionLinkMissing { .. })));
}
