//! Junction `<boundary>` and `<elevationGrid>`: the area of a junction and
//! the height of its ground.
//!
//! `tests/data/junction_areas.xodr` is generated by `junction_areas.py`.

use xodr::{load_file_with_provenance, JunctionArea, Warning};

const FIXTURE: &str = "tests/data/junction_areas.xodr";

fn areas() -> (Vec<JunctionArea>, Vec<Warning>) {
    let (net, prov) = load_file_with_provenance(FIXTURE).unwrap();
    (net.junction_areas().to_vec(), prov.warnings)
}

/// Twice the area a ring encloses in plan, positive counter-clockwise.
fn area(ring: &[xodr::Point]) -> f32 {
    ring.iter()
        .zip(ring.iter().cycle().skip(1))
        .map(|(a, b)| a.x * b.y - b.x * a.y)
        .sum::<f32>()
        / 2.0
}

#[test]
fn a_boundary_runs_counter_clockwise_round_its_segments_on_the_road_surface() {
    let (areas, _) = areas();
    let seven = &areas[0];
    assert_eq!(seven.od_id, "7");
    assert!(
        (area(&seven.boundary) - 70.0).abs() < 1e-3,
        "{}",
        area(&seven.boundary)
    );
    let corners = [(20.0, -3.5), (30.0, -3.5), (30.0, 3.5), (20.0, 3.5)];
    for (x, y) in corners {
        assert!(
            seven
                .boundary
                .iter()
                .any(|p| (p.x - x).abs() < 1e-4 && (p.y - y).abs() < 1e-4 && p.z.abs() < 1e-6),
            "no corner at ({x}, {y})"
        );
    }
}

#[test]
fn the_grid_gives_its_heights_at_its_points_and_between_them() {
    let (areas, _) = areas();
    let seven = &areas[0];
    let at = |x, y| seven.height_at(x, y).unwrap();
    assert!((at(22.0, 0.0) - 0.2).abs() < 1e-9);
    assert!((at(26.0, 4.0)).abs() < 1e-9);
    // The cubic through the line's heights 0, 0.2, 0.2 and 0 rises between
    // the two middle ones: to 0.225 halfway, with slopes of 0.1 and -0.1.
    assert!((at(24.0, 0.0) - 0.225).abs() < 1e-9);
    let between = at(20.0, 0.0);
    assert!(between > 0.0 && between < 0.2, "{between}");
    assert!(seven.height_at(31.0, 0.0).is_none());
    assert!(seven.height_at(24.0, 4.5).is_none());
}

#[test]
fn the_mesh_covers_the_boundary_at_the_grids_height() {
    let (areas, _) = areas();
    let mesh = areas[0].mesh();
    mesh.validate().unwrap();
    let covered: f32 = mesh
        .indices
        .chunks_exact(3)
        .map(|t| {
            let [a, b, c] = [0, 1, 2].map(|k| mesh.vertices[t[k] as usize]);
            ((b.x - a.x) * (c.y - a.y) - (b.y - a.y) * (c.x - a.x)) / 2.0
        })
        .sum();
    assert!((covered - 70.0).abs() < 1e-2, "{covered}");
    let top = mesh.vertices.iter().map(|v| v.z).fold(0.0_f32, f32::max);
    assert!(top > 0.2 && top <= 0.225 + 1e-6, "{top}");
    assert!(mesh.normals.iter().all(|n| n.z > 0.9));
}

#[test]
fn the_crate_warns_that_the_grid_leaves_the_roads_as_they_are() {
    let (_, warnings) = areas();
    assert!(warnings.contains(&Warning::ElevationGridNotApplied {
        junction_id: "7".into()
    }));
}

#[test]
fn a_clockwise_boundary_with_a_segment_it_cannot_place_is_turned_and_warned_of() {
    let (areas, warnings) = areas();
    let eight = &areas[1];
    assert_eq!(eight.od_id, "8");
    assert!(area(&eight.boundary) > 0.0);
    assert!(eight.grid.is_none());
    let about_eight: Vec<String> = warnings
        .iter()
        .filter(|w| w.to_string().contains("junction \"8\""))
        .map(|w| w.to_string())
        .collect();
    assert_eq!(
        about_eight,
        [
            "junction \"8\": <boundary> segment on road \"99\" dropped",
            "junction \"8\": <boundary> segments leave a 10.00 m gap, joined straight",
            "junction \"8\": <boundary> runs clockwise, turned round",
        ]
    );
    let dropped = warnings
        .iter()
        .find(|w| matches!(w, Warning::BoundarySegmentDropped { .. }))
        .unwrap();
    assert_eq!(dropped.road_id(), "99");
}

/// Road 1 runs 20 m along +X with right lanes -1 and -2, 3.5 m each.
/// Junction 7's boundary is one joint across both, at road 1's end. Junction
/// 8's grid has no `<planView>`, and junction 9's is on an arc.
const ONE_SIDE: &str = r#"<OpenDRIVE>
  <road id="1" length="20" junction="-1">
    <planView><geometry s="0" x="0" y="0" hdg="0" length="20"><line/></geometry></planView>
    <lanes><laneSection s="0"><center><lane id="0" type="none"/></center><right>
      <lane id="-1" type="driving"><width sOffset="0" a="3.5" b="0" c="0" d="0"/></lane>
      <lane id="-2" type="driving"><width sOffset="0" a="3.5" b="0" c="0" d="0"/></lane>
    </right></laneSection></lanes>
  </road>
  <junction id="7">
    <boundary><segment type="joint" roadId="1" contactPoint="end" jointLaneStart="-2" jointLaneEnd="-1"/></boundary>
  </junction>
  <junction id="8">
    <elevationGrid sStart="0" gridSpacing="2"><elevation center="0"/><elevation center="0"/></elevationGrid>
  </junction>
  <junction id="9">
    <planView><geometry s="0" x="0" y="0" hdg="0" length="10"><arc curvature="0.2"/></geometry></planView>
    <elevationGrid sStart="0" gridSpacing="2"><elevation center="0"/><elevation center="0"/></elevationGrid>
  </junction>
</OpenDRIVE>"#;

#[test]
fn a_joint_across_two_lanes_on_one_side_crosses_both_whole() {
    let (net, _) = xodr::load_str_with_provenance(ONE_SIDE).unwrap();
    let area = net
        .junction_areas()
        .iter()
        .find(|a| a.od_id == "7")
        .unwrap();
    let ys: Vec<f32> = area.boundary.iter().map(|p| p.y).collect();
    assert_eq!(ys, [-7.0, -3.5, 0.0]);
}

#[test]
fn a_boundary_of_one_segment_is_not_closed() {
    let (_, prov) = xodr::load_str_with_provenance(ONE_SIDE).unwrap();
    assert!(prov.warnings.iter().any(|w| matches!(
        w,
        Warning::BoundaryNotClosed { junction_id, gap } if junction_id == "7" && (gap - 7.0).abs() < 1e-3
    )));
}

#[test]
fn a_grid_without_one_straight_reference_line_is_dropped_with_a_warning() {
    let (net, prov) = xodr::load_str_with_provenance(ONE_SIDE).unwrap();
    assert!(net.junction_areas().iter().all(|a| a.od_id == "7"));
    for id in ["8", "9"] {
        assert!(prov.warnings.contains(&Warning::ElevationGridDropped {
            junction_id: id.into()
        }));
    }
}

/// Rows of different widths: a point on the edge of a square the grid covers
/// whole gets its height, though the square beyond that edge is missing a
/// corner.
#[test]
fn a_point_on_the_edge_of_a_covered_square_has_a_height_on_ragged_rows() {
    let grid = xodr::ElevationGrid {
        origin: [0.0, 0.0],
        heading: 0.0,
        s_start: 0.0,
        spacing: 1.0,
        rows: vec![
            xodr::GridRow {
                center: 1.0,
                left: vec![2.0, 3.0],
                right: Vec::new(),
            },
            xodr::GridRow {
                center: 1.0,
                left: vec![2.0],
                right: Vec::new(),
            },
        ],
    };
    let at_edge = grid.height(0.5, 1.0).expect("on the covered square's edge");
    assert!((at_edge - 2.0).abs() < 1e-9, "{at_edge}");
    assert!(grid.height(0.5, 0.5).is_some(), "inside it");
}

#[test]
fn a_boundary_segment_off_its_road_is_dropped_with_a_warning() {
    let xodr = std::fs::read_to_string(FIXTURE).unwrap().replacen(
        r#"<segment type="lane" roadId="10" boundaryLane="-1" sStart="start" sEnd="end"/>"#,
        r#"<segment type="lane" roadId="10" boundaryLane="-1" sStart="start" sEnd="500"/>"#,
        1,
    );
    let (_, prov) = xodr::load_str_with_provenance(&xodr).unwrap();
    assert!(prov.warnings.contains(&Warning::BoundarySegmentDropped {
        junction_id: "7".into(),
        road_id: "10".into(),
    }));
}
