//! `<junctionGroup>`: junctions routing should see as one.
//!
//! `tests/data/junction_groups.xodr` is generated by `junction_groups.py`.

use libopendrive::{
    load_file_with_provenance, load_str_with_provenance, JunctionGroup, JunctionGroupKind, Warning,
};

const FIXTURE: &str = "tests/data/junction_groups.xodr";

#[test]
fn a_group_names_its_junctions_and_what_they_are() {
    let (net, _) = load_file_with_provenance(FIXTURE).unwrap();
    assert_eq!(
        net.junction_groups(),
        [
            JunctionGroup {
                od_id: "1".into(),
                name: "Ring".into(),
                kind: JunctionGroupKind::Roundabout,
                junctions: vec!["5".into(), "6".into()],
            },
            JunctionGroup {
                od_id: "2".into(),
                name: String::new(),
                kind: JunctionGroupKind::Unknown,
                junctions: vec!["5".into()],
            },
        ]
    );
}

#[test]
fn a_road_in_a_grouped_junction_finds_its_group() {
    let (net, _) = load_file_with_provenance(FIXTURE).unwrap();
    let road = |id: &str| net.road_by_od_id(id).unwrap();
    assert_eq!(road("10").junction(), Some("5"));
    assert_eq!(road("1").junction(), None);
    let groups = |id: &str| {
        net.junction_groups_of(road(id).id())
            .map(|g| g.od_id.as_str())
            .collect::<Vec<_>>()
    };
    assert_eq!(groups("11"), ["1"]);
    assert_eq!(groups("10"), ["1", "2"]);
    assert!(groups("2").is_empty());
}

#[test]
fn a_reference_to_a_missing_junction_and_an_unknown_type_warn() {
    let (_, prov) = load_file_with_provenance(FIXTURE).unwrap();
    let group: Vec<String> = prov
        .warnings
        .iter()
        .filter(|w| {
            matches!(
                w,
                Warning::JunctionReferenceDropped { .. } | Warning::UnknownJunctionGroupType { .. }
            )
        })
        .map(|w| w.to_string())
        .collect();
    assert_eq!(
        group,
        [
            "junction group \"1\": <junctionReference> to junction \"9\" dropped, the file has no such junction",
            "junction group \"2\": type \"spiral\" read as unknown",
        ]
    );
}

#[test]
fn a_group_without_a_type_or_repeating_a_junction_is_read_once_with_a_warning() {
    let xml = std::fs::read_to_string(FIXTURE).unwrap().replace(
        r#"<junctionGroup id="2" type="spiral"><junctionReference junction="5"/>"#,
        r#"<junctionGroup id="2"><junctionReference junction="5"/><junctionReference junction="5"/>"#,
    );
    let (net, prov) = load_str_with_provenance(&xml).unwrap();
    let group = net
        .junction_groups()
        .iter()
        .find(|g| g.od_id == "2")
        .unwrap();
    assert_eq!(group.kind, JunctionGroupKind::Unknown);
    assert_eq!(group.junctions, ["5"]);
    assert!(prov.warnings.contains(&Warning::UnknownJunctionGroupType {
        group_id: "2".into(),
        kind: String::new(),
    }));
}
