//! Lane rules, access and materials: a lane's own `<rule>`s, `<access>`es
//! and `<material>`s.
//!
//! `tests/data/lane_rules.xodr` is generated by `lane_rules.py`. Its road
//! is a straight along +X, so a right lane's distance along its centerline
//! is the road's `s`, less the start of its lane section.

use libopendrive::{
    load_file_with_provenance, Access, Along, LaneId, Material, Provenance, RoadNetwork, Warning,
};

const FIXTURE: &str = "tests/data/lane_rules.xodr";

fn fixture() -> (RoadNetwork, Provenance) {
    load_file_with_provenance(FIXTURE).expect("the fixture loads")
}

/// The baked lane `od_id` of lane section `section`.
fn lane(prov: &Provenance, section: usize, od_id: i32) -> LaneId {
    prov.lanes
        .iter()
        .find(|p| p.section == section && p.od_id == od_id)
        .unwrap_or_else(|| panic!("section {section} lane {od_id}"))
        .lane
}

/// Each stretch of `list` on `lane`, as `(from, to, value)`, with the ends
/// rounded to the millimetre.
fn on<T: Clone>(list: &[Along<T>], lane: LaneId) -> Vec<(f32, f32, T)> {
    let mm = |v: f32| (v * 1000.0).round() / 1000.0;
    list.iter()
        .filter(|a| a.lane == lane)
        .map(|a| (mm(a.from), mm(a.to), a.value.clone()))
        .collect()
}

fn users(names: &[&str]) -> Vec<String> {
    names.iter().map(|n| n.to_string()).collect()
}

fn material(surface: &str, friction: f32, roughness: Option<f32>) -> Material {
    Material {
        surface: surface.into(),
        friction: Some(friction),
        roughness,
    }
}

#[test]
fn a_rule_holds_until_the_next_one_and_one_without_a_value_is_skipped() {
    let (net, prov) = fixture();
    let lane = lane(&prov, 0, -1);
    assert_eq!(
        on(net.lane_rules(), lane),
        vec![
            (0.0, 30.0, "no stopping at any time".to_string()),
            (30.0, 60.0, "car pool".to_string()),
        ]
    );
    assert_eq!(net.lane_rule_at(lane, 45.0), Some("car pool"));
}

#[test]
fn a_rule_ends_with_its_lane_section() {
    let (net, prov) = fixture();
    assert!(on(net.lane_rules(), lane(&prov, 1, -1)).is_empty());
}

/// A lane's centerline runs along +s whichever way its traffic drives, so a
/// left lane's stretches start at its `s = 0` end too.
#[test]
fn a_left_lane_measures_its_rules_along_its_centerline() {
    let (net, prov) = fixture();
    let lane = lane(&prov, 0, 1);
    assert_eq!(
        on(net.lane_rules(), lane),
        vec![
            (0.0, 20.0, "disabled parking".to_string()),
            (20.0, 60.0, "no stopping at any time".to_string()),
        ]
    );
}

#[test]
fn access_allows_only_its_road_users_until_a_deny_of_none() {
    let (net, prov) = fixture();
    let lane = lane(&prov, 0, -1);
    assert_eq!(
        on(net.lane_access(), lane),
        vec![(0.0, 40.0, Access::Allow(users(&["bus", "taxi"])))]
    );
    assert_eq!(net.lane_access_at(lane, 50.0), None);
}

#[test]
fn old_style_access_at_one_offset_merges_and_one_without_a_rule_is_dropped() {
    let (net, prov) = fixture();
    let lane = lane(&prov, 0, -2);
    assert_eq!(
        on(net.lane_access(), lane),
        vec![(10.0, 30.0, Access::Deny(users(&["truck", "bicycle"])))]
    );
    assert_eq!(
        prov.warnings,
        vec![Warning::AccessDropped {
            road_id: "0".into(),
            s: 30.0,
            lane: -2,
            rule: String::new(),
        }]
    );
}

#[test]
fn materials_hold_in_order_along_the_lane() {
    let (net, prov) = fixture();
    assert_eq!(
        on(net.lane_materials(), lane(&prov, 0, -1)),
        vec![
            (0.0, 20.0, material("asphalt", 0.9, Some(0.002))),
            (20.0, 60.0, material("gravel", 0.6, None)),
        ]
    );
    let sorted = lane(&prov, 0, -2);
    assert_eq!(
        on(net.lane_materials(), sorted),
        vec![
            (5.0, 25.0, material("asphalt", 0.9, None)),
            (25.0, 60.0, material("concrete", 0.8, None)),
        ]
    );
    assert_eq!(net.lane_material_at(sorted, 2.0), None);
}

#[cfg(feature = "serde")]
#[test]
fn rules_access_and_materials_survive_serde() {
    let (net, _) = fixture();
    let json = serde_json::to_string(&net).expect("serialize");
    let back: RoadNetwork = serde_json::from_str(&json).expect("deserialize");
    assert_eq!(back, net);
    assert!(!back.lane_access().is_empty());
}
