//! A lane's `direction`, which overrides the way its side of the road runs.
//!
//! `tests/data/lane_direction.xodr` is generated by `lane_direction.py`.

use libopendrive::{
    load_file_with_provenance, load_str_with_provenance, Advance, Direction, Lane, LaneId,
    LanePosition, Point, Provenance, RoadNetwork, Warning,
};

const FIXTURE: &str = "tests/data/lane_direction.xodr";

fn fixture() -> (RoadNetwork, Provenance) {
    load_file_with_provenance(FIXTURE).unwrap()
}

fn id(prov: &Provenance, road: &str, od_id: i32) -> LaneId {
    prov.lanes
        .iter()
        .find(|p| p.road_id == road && p.od_id == od_id)
        .unwrap()
        .lane
}

fn lane<'a>(net: &'a RoadNetwork, prov: &Provenance, road: &str, od_id: i32) -> &'a Lane {
    net.lane(id(prov, road, od_id)).unwrap()
}

#[test]
fn a_reversed_lane_runs_against_its_side_and_a_both_lane_either_way() {
    let (net, prov) = fixture();
    let direction = |od_id| lane(&net, &prov, "0", od_id).direction;
    assert_eq!(direction(1), Direction::Backward);
    assert_eq!(direction(-1), Direction::Forward);
    assert_eq!(direction(-2), Direction::Backward);
    assert_eq!(direction(-3), Direction::Both);
    assert_eq!(direction(-4), Direction::Forward);
}

#[test]
fn links_follow_each_lanes_direction() {
    let (net, prov) = fixture();
    let successors = |road, od_id| lane(&net, &prov, road, od_id).successors.clone();
    assert_eq!(successors("0", -1), [id(&prov, "1", -1)]);
    assert!(successors("0", -2).is_empty());
    assert_eq!(successors("1", -2), [id(&prov, "0", -2)]);
    assert_eq!(successors("0", -3), [id(&prov, "1", -3)]);
    assert_eq!(successors("1", -3), [id(&prov, "0", -3)]);
    let both = lane(&net, &prov, "0", -3);
    assert_eq!(both.predecessors, [id(&prov, "1", -3)]);
}

#[test]
fn a_lane_running_the_other_way_is_no_lane_change() {
    let (net, prov) = fixture();
    let neighbors = |od_id| lane(&net, &prov, "0", od_id).neighbors.clone();
    assert!(neighbors(-1).is_empty());
    assert!(neighbors(-2).is_empty());
    assert!(neighbors(-3).is_empty());
}

#[test]
fn an_unknown_direction_is_standard_with_a_warning() {
    let (_, prov) = fixture();
    let unknown: Vec<_> = prov
        .warnings
        .iter()
        .filter(|w| matches!(w, Warning::UnknownLaneDirection { .. }))
        .collect();
    assert_eq!(
        unknown,
        [
            &Warning::UnknownLaneDirection {
                road_id: "0".into(),
                section: 0,
                lane: -4,
                direction: "sideways".into(),
            },
            &Warning::UnknownLaneDirection {
                road_id: "1".into(),
                section: 0,
                lane: -4,
                direction: "sideways".into(),
            },
        ]
    );
    assert!(!prov
        .warnings
        .iter()
        .any(|w| matches!(w, Warning::LinkGap { .. })));
}

/// The offset is toward `+t` wherever the branch goes, so on one road it
/// stays where it is across the lane.
#[test]
fn from_a_both_lane_a_move_goes_each_way() {
    let (net, prov) = fixture();
    let from = LanePosition {
        lane: id(&prov, "0", -3),
        s: 45.0,
        offset: 0.5,
    };
    let mut ends: Vec<_> = net
        .advance(from, 10.0)
        .into_iter()
        .map(|b| match b {
            Advance::Reached(at) => (at.lane, (at.s * 1000.0).round() / 1000.0, at.offset, None),
            Advance::DeadEnd { at, short } => (at.lane, at.s, at.offset, Some(short)),
        })
        .collect();
    ends.sort_by(|a, b| a.1.total_cmp(&b.1));
    assert_eq!(
        ends,
        [
            (id(&prov, "1", -3), 5.0, 0.5, None),
            (id(&prov, "0", -3), 35.0, 0.5, None),
        ]
    );
}

#[test]
fn a_route_drives_a_both_lane_the_way_it_needs() {
    let (net, _) = fixture();
    let route = net
        .route(Point::new(90.0, -8.75, 0.0), Point::new(10.0, -8.75, 0.0))
        .expect("a route");
    let x: Vec<f32> = route.iter().map(|p| p.x).collect();
    assert!(x.windows(2).all(|w| w[1] <= w[0] + 1e-3), "{x:?}");
}

/// Road 1 runs one way into junction 5 at its end. Connecting road 6, two
/// way, runs from road 1 into road 2, two way, which names the junction as
/// its predecessor. The junction's only connection comes from road 1, as in
/// ASAM's `Ex_Bidirectional_Junction`.
const INTO_TWO_WAY: &str = r#"<OpenDRIVE>
  <road id="1" length="20" junction="-1">
    <link><successor elementType="junction" elementId="5"/></link>
    <planView><geometry s="0" x="0" y="0" hdg="0" length="20"><line/></geometry></planView>
    <lanes><laneSection s="0"><center><lane id="0" type="none"/></center>
      <right><lane id="-1" type="driving"><width sOffset="0" a="3.5" b="0" c="0" d="0"/></lane></right>
    </laneSection></lanes>
  </road>
  <road id="6" length="10" junction="5">
    <link><predecessor elementType="road" elementId="1" contactPoint="end"/><successor elementType="road" elementId="2" contactPoint="start"/></link>
    <planView><geometry s="0" x="20" y="0" hdg="0" length="10"><line/></geometry></planView>
    <lanes><laneSection s="0"><center><lane id="0" type="none"/></center>
      <right><lane id="-1" type="driving" direction="both"><link><predecessor id="-1"/><successor id="-1"/></link><width sOffset="0" a="3.5" b="0" c="0" d="0"/></lane></right>
    </laneSection></lanes>
  </road>
  <road id="2" length="20" junction="-1">
    <link><predecessor elementType="junction" elementId="5"/></link>
    <planView><geometry s="0" x="30" y="0" hdg="0" length="20"><line/></geometry></planView>
    <lanes><laneSection s="0"><center><lane id="0" type="none"/></center>
      <right><lane id="-1" type="driving" direction="both"><width sOffset="0" a="3.5" b="0" c="0" d="0"/></lane></right>
    </laneSection></lanes>
  </road>
  <junction id="5">
    <connection id="0" incomingRoad="1" connectingRoad="6" contactPoint="start"><laneLink from="-1" to="-1"/></connection>
  </junction>
</OpenDRIVE>"#;

#[test]
fn two_way_lanes_that_join_lead_into_each_other_both_ways() {
    let (net, prov) = load_str_with_provenance(INTO_TWO_WAY).unwrap();
    let connecting = id(&prov, "6", -1);
    let beyond = id(&prov, "2", -1);
    assert!(lane(&net, &prov, "6", -1).successors.contains(&beyond));
    assert!(lane(&net, &prov, "2", -1).successors.contains(&connecting));
    assert!(lane(&net, &prov, "1", -1).predecessors.is_empty());
}

#[test]
fn a_deprecated_bidirectional_lane_runs_both_ways() {
    let xml = INTO_TWO_WAY.replace(
        r#"<lane id="-1" type="driving" direction="both"><width"#,
        r#"<lane id="-1" type="bidirectional"><width"#,
    );
    let (net, prov) = load_str_with_provenance(&xml).unwrap();
    assert_eq!(lane(&net, &prov, "2", -1).direction, Direction::Both);
}
