//! Lane borders: `<lane><border>` giving a lane's outer edge as a `t`.
//!
//! `tests/data/lane_borders.xodr` is generated by `lane_borders.py`. Every
//! road there is a straight along +X, so a lane's borders are its
//! centerline's `y` less the road's, plus or minus half its width.

use libopendrive::{load_file_with_provenance, Lane, Provenance, RoadNetwork, Warning};

const FIXTURE: &str = "tests/data/lane_borders.xodr";

/// Where each road's reference line runs, as `y`.
const ROAD_Y: [f32; 5] = [0.0, 20.0, 40.0, 60.0, 80.0];

fn fixture() -> (RoadNetwork, Provenance) {
    load_file_with_provenance(FIXTURE).expect("the fixture loads")
}

/// The baked lane `od_id` of lane section `section` on road `road`.
fn lane<'a>(
    net: &'a RoadNetwork,
    prov: &Provenance,
    road: usize,
    section: usize,
    od_id: i32,
) -> &'a Lane {
    let p = prov
        .lanes
        .iter()
        .find(|p| p.road_id == road.to_string() && p.section == section && p.od_id == od_id)
        .unwrap_or_else(|| panic!("road {road} section {section} lane {od_id}"));
    net.lane(p.lane).expect("a baked lane")
}

/// Each centerline vertex of `lane` on road `road`, as `(s, inner t, outer
/// t)`. `s` is along the road.
fn borders(lane: &Lane, road: usize, od_id: i32) -> Vec<(f32, f32, f32)> {
    let sign = od_id.signum() as f32;
    lane.center
        .points()
        .iter()
        .enumerate()
        .map(|(i, p)| {
            let width = lane.widths.get(i).copied().unwrap_or(lane.width);
            let t = p.y - ROAD_Y[road];
            (p.x, t - sign * width / 2.0, t + sign * width / 2.0)
        })
        .collect()
}

fn close(a: f32, b: f32) -> bool {
    (a - b).abs() < 1e-3
}

/// Lane -2's border on road 0, `ds` metres into its section.
fn opening(ds: f32) -> f32 {
    let ds = ds.min(20.0);
    -3.5 - 3.0 * 3.5 / 400.0 * ds * ds + 2.0 * 3.5 / 8000.0 * ds * ds * ds
}

#[test]
fn an_opening_lane_follows_its_border() {
    let (net, prov) = fixture();
    let opened = lane(&net, &prov, 0, 1, -2);
    assert!(close(opened.widths[0], 0.0), "it opens out of nothing");
    for (s, inner, outer) in borders(opened, 0, -2) {
        assert!(close(inner, -3.5), "inner {inner} at s {s}");
        assert!(close(outer, opening(s - 30.0)), "outer {outer} at s {s}");
    }
}

#[test]
fn a_border_lane_stacks_on_a_width_lane_and_a_width_lane_on_it() {
    let (net, prov) = fixture();
    for (od_id, inner, outer) in [(-1, 0.0, -3.5), (-2, -3.5, -6.0), (-3, -6.0, -8.0)] {
        for (s, i, o) in borders(lane(&net, &prov, 1, 0, od_id), 1, od_id) {
            assert!(close(i, inner) && close(o, outer), "lane {od_id} at s {s}");
        }
    }
}

#[test]
fn a_lane_with_widths_and_borders_follows_its_widths() {
    let (net, prov) = fixture();
    for (od_id, inner, outer) in [(-1, 0.0, -3.5), (-2, -3.5, -5.5)] {
        for (s, i, o) in borders(lane(&net, &prov, 2, 0, od_id), 2, od_id) {
            assert!(close(i, inner) && close(o, outer), "lane {od_id} at s {s}");
        }
    }
}

#[test]
fn a_border_is_measured_from_the_reference_line_not_the_lane_offset() {
    let (net, prov) = fixture();
    for (od_id, outer) in [(1, 4.0), (-1, -3.0)] {
        for (s, i, o) in borders(lane(&net, &prov, 3, 0, od_id), 3, od_id) {
            assert!(close(i, 1.0) && close(o, outer), "lane {od_id} at s {s}");
        }
    }
    assert!(prov.warnings.contains(&Warning::BorderWithLaneOffset {
        road_id: "3".into(),
        section: 0,
        lane: -1,
    }));
}

#[test]
fn a_border_inside_its_inner_lane_gives_the_lane_no_width() {
    let (net, prov) = fixture();
    for (s, inner, outer) in borders(lane(&net, &prov, 4, 0, -2), 4, -2) {
        let want = (-5.0 + 0.05 * s).min(-3.5);
        assert!(close(inner, -3.5) && close(outer, want), "{outer} at s {s}");
    }
    let crossed = prov.warnings.iter().find_map(|w| match w {
        Warning::BorderCrossesInnerLane {
            road_id,
            section: 0,
            lane: -2,
            s,
        } if road_id == "4" => Some(*s),
        _ => None,
    });
    let s = crossed.expect("a crossing warning");
    assert!(s > 30.0 && s <= 32.0, "first seen crossing at {s}");
}

#[test]
fn each_border_the_spec_forbids_raises_one_warning() {
    let (_, prov) = fixture();
    let at = |road: &str, lane| (road.to_string(), 0, lane);
    let found: Vec<_> = prov
        .warnings
        .iter()
        .map(|w| match w {
            Warning::WidthAndBorder {
                road_id,
                section,
                lane,
            } => ("width and border", (road_id.clone(), *section, *lane)),
            Warning::BorderWithLaneOffset {
                road_id,
                section,
                lane,
            } => ("lane offset", (road_id.clone(), *section, *lane)),
            Warning::BorderCrossesInnerLane {
                road_id,
                section,
                lane,
                ..
            } => ("crossing", (road_id.clone(), *section, *lane)),
            other => panic!("unexpected {other}"),
        })
        .collect();
    assert_eq!(
        found,
        [
            ("width and border", at("1", -2)),
            ("width and border", at("2", -1)),
            ("lane offset", at("3", 1)),
            ("lane offset", at("3", -1)),
            ("crossing", at("4", -2)),
        ]
    );
}

#[test]
fn a_border_lane_is_not_dropped() {
    let (net, prov) = fixture();
    assert!(!prov
        .warnings
        .iter()
        .any(|w| matches!(w, Warning::LaneDropped { .. })));
    assert_eq!(net.lanes().len(), 15);
}

#[test]
fn marks_run_along_a_border() {
    let (net, prov) = fixture();
    let (mark, _) = net
        .road_marks()
        .iter()
        .zip(&prov.road_marks)
        .find(|(_, p)| p.road_id == "0" && p.section == 1 && p.od_lane_id == -2)
        .expect("lane -2's mark");
    let pieces = &mark.lines[0].pieces;
    assert!(!pieces.is_empty());
    for [a, _, _, d] in pieces {
        let t = (a.y + d.y) / 2.0;
        assert!(close(t, opening(a.x - 30.0)), "mark at {t}, s {}", a.x);
    }
}

#[test]
fn border_lanes_keep_their_links_and_neighbours() {
    let (net, prov) = fixture();
    let first = lane(&net, &prov, 0, 0, -1);
    let second = lane(&net, &prov, 0, 1, -1);
    let opened = lane(&net, &prov, 0, 1, -2);
    assert_eq!(first.successors, [second.id]);
    assert_eq!(second.predecessors, [first.id]);
    assert_eq!(second.neighbors, [opened.id]);
    assert_eq!(opened.neighbors, [second.id]);
    let left = lane(&net, &prov, 0, 0, 1);
    assert_eq!(left.predecessors, [lane(&net, &prov, 0, 1, 1).id]);
}

#[test]
fn the_border_fixture_tessellates_into_a_valid_mesh() {
    let (net, _) = fixture();
    net.surface_mesh().validate().expect("a valid mesh");
}
