//! Whether a road mark lets a vehicle change into the lane beside it.
//!
//! `tests/data/lane_change.xodr` is generated by `lane_change.py`. Its one
//! road runs along +X in right-hand traffic, so the left of lanes -1 to -3
//! is `+t`, and the left of lane 1 is `-t`.

use libopendrive::{
    load_file_with_provenance, load_str_with_provenance, LanePosition, Provenance, RoadNetwork,
};

const FIXTURE: &str = "tests/data/lane_change.xodr";

fn fixture() -> (RoadNetwork, Provenance) {
    load_file_with_provenance(FIXTURE).unwrap()
}

/// Lane `od_id` of road 0, at road `s`, on its center.
fn at(prov: &Provenance, od_id: i32, s: f64) -> LanePosition {
    let lane = prov.lanes.iter().find(|p| p.od_id == od_id).unwrap().lane;
    LanePosition {
        lane,
        s,
        offset: 0.0,
    }
}

#[test]
fn a_mark_with_lane_change_none_forbids_crossing_it_and_one_without_allows_it() {
    let (net, prov) = fixture();
    assert_eq!(net.may_change_left(at(&prov, -1, 10.0)), Some(false));
    assert_eq!(net.may_change_left(at(&prov, -1, 70.0)), Some(true));
}

#[test]
fn increase_and_decrease_allow_crossing_one_way() {
    let (net, prov) = fixture();
    assert_eq!(net.may_change_left(at(&prov, -2, 10.0)), Some(true));
    assert_eq!(net.may_change_right(at(&prov, -1, 10.0)), Some(false));
    assert_eq!(net.may_change_right(at(&prov, -2, 30.0)), Some(true));
    assert_eq!(net.may_change_left(at(&prov, -3, 30.0)), Some(false));
}

#[test]
fn the_left_follows_the_lanes_traffic() {
    let (net, prov) = fixture();
    assert_eq!(net.may_change_left(at(&prov, 1, 10.0)), Some(false));
    assert_eq!(net.may_change_left(at(&prov, 1, 70.0)), Some(true));
    assert_eq!(net.may_change_right(at(&prov, 1, 70.0)), None);
}

#[test]
fn the_mark_starting_where_two_meet_answers() {
    let (net, prov) = fixture();
    assert_eq!(net.may_change_left(at(&prov, -1, 50.0)), Some(true));
}

#[test]
fn no_lane_no_mark_or_an_unknown_lane_change_gives_no_answer() {
    let (net, prov) = fixture();
    assert_eq!(net.may_change_right(at(&prov, -3, 30.0)), None);
    assert_eq!(net.may_change_right(at(&prov, -2, 10.0)), None);
    assert_eq!(net.may_change_right(at(&prov, -2, 70.0)), None);
}

#[cfg(feature = "serde")]
#[test]
fn lane_changes_survive_a_serde_round_trip() {
    let (net, prov) = fixture();
    let back: RoadNetwork = serde_json::from_str(&serde_json::to_string(&net).unwrap()).unwrap();
    assert_eq!(back.may_change_left(at(&prov, -1, 70.0)), Some(true));
    assert_eq!(back.may_change_right(at(&prov, -2, 30.0)), Some(true));
}

/// A road with lanes 2, 1, -1 and -2 under `rule`, whose center line
/// forbids crossing and whose other inner borders allow it.
fn two_way(rule: &str) -> (RoadNetwork, Provenance) {
    let mark = |c: &str| format!(r#"<roadMark sOffset="0" type="broken" laneChange="{c}"/>"#);
    let lane = |id: i32, mark: &str| {
        format!(
            r#"<lane id="{id}" type="driving"><width sOffset="0" a="3.5" b="0" c="0" d="0"/>{mark}</lane>"#
        )
    };
    let xodr = format!(
        r#"<OpenDRIVE><header/><road id="0" length="100" junction="-1" rule="{rule}">
<planView><geometry s="0" x="0" y="0" hdg="0" length="100"><line/></geometry></planView>
<lanes><laneSection s="0"><left>{}{}</left><center><lane id="0" type="none">{}</lane></center><right>{}{}</right></laneSection></lanes>
</road></OpenDRIVE>"#,
        lane(2, ""),
        lane(1, &mark("both")),
        mark("none"),
        lane(-1, &mark("both")),
        lane(-2, ""),
    );
    load_str_with_provenance(&xodr).unwrap()
}

#[test]
fn left_hand_traffic_puts_the_center_line_on_the_right() {
    let (net, prov) = two_way("LHT");
    assert_eq!(net.may_change_right(at(&prov, 1, 50.0)), Some(false));
    assert_eq!(net.may_change_left(at(&prov, 1, 50.0)), Some(true));
    assert_eq!(net.may_change_right(at(&prov, -1, 50.0)), Some(false));
    assert_eq!(net.may_change_left(at(&prov, -1, 50.0)), Some(true));
    assert_eq!(net.may_change_left(at(&prov, 2, 50.0)), None);

    let (net, prov) = two_way("RHT");
    assert_eq!(net.may_change_left(at(&prov, -1, 50.0)), Some(false));
    assert_eq!(net.may_change_right(at(&prov, -1, 50.0)), Some(true));
}
