//! Whether a road mark lets a vehicle change into the lane beside it.
//!
//! `tests/data/lane_change.xodr` is generated by `lane_change.py`. Its one
//! road runs along +X in right-hand traffic, so the left of lanes -1 to -3
//! is `+t`, and the left of lane 1 is `-t`.

use libopendrive::{load_file_with_provenance, LanePosition, Provenance, RoadNetwork};

const FIXTURE: &str = "tests/data/lane_change.xodr";

fn fixture() -> (RoadNetwork, Provenance) {
    load_file_with_provenance(FIXTURE).unwrap()
}

/// Lane `od_id` of road 0, at road `s`, on its center.
fn at(prov: &Provenance, od_id: i32, s: f64) -> LanePosition {
    let lane = prov.lanes.iter().find(|p| p.od_id == od_id).unwrap().lane;
    LanePosition {
        lane,
        s,
        offset: 0.0,
    }
}

#[test]
fn a_mark_with_lane_change_none_forbids_crossing_it_and_one_without_allows_it() {
    let (net, prov) = fixture();
    assert_eq!(net.may_change_left(at(&prov, -1, 10.0)), Some(false));
    assert_eq!(net.may_change_left(at(&prov, -1, 70.0)), Some(true));
}

#[test]
fn increase_and_decrease_allow_crossing_one_way() {
    let (net, prov) = fixture();
    assert_eq!(net.may_change_left(at(&prov, -2, 10.0)), Some(true));
    assert_eq!(net.may_change_right(at(&prov, -1, 10.0)), Some(false));
    assert_eq!(net.may_change_right(at(&prov, -2, 30.0)), Some(true));
    assert_eq!(net.may_change_left(at(&prov, -3, 30.0)), Some(false));
}

#[test]
fn the_left_follows_the_lanes_traffic() {
    let (net, prov) = fixture();
    assert_eq!(net.may_change_left(at(&prov, 1, 10.0)), Some(false));
    assert_eq!(net.may_change_left(at(&prov, 1, 70.0)), Some(true));
    assert_eq!(net.may_change_right(at(&prov, 1, 70.0)), None);
}

#[test]
fn the_mark_starting_where_two_meet_answers() {
    let (net, prov) = fixture();
    assert_eq!(net.may_change_left(at(&prov, -1, 50.0)), Some(true));
}

#[test]
fn no_lane_no_mark_or_an_unknown_lane_change_gives_no_answer() {
    let (net, prov) = fixture();
    assert_eq!(net.may_change_right(at(&prov, -3, 30.0)), None);
    assert_eq!(net.may_change_right(at(&prov, -2, 10.0)), None);
    assert_eq!(net.may_change_right(at(&prov, -2, 70.0)), None);
}

#[cfg(feature = "serde")]
#[test]
fn lane_changes_survive_a_serde_round_trip() {
    let (net, prov) = fixture();
    let back: RoadNetwork = serde_json::from_str(&serde_json::to_string(&net).unwrap()).unwrap();
    assert_eq!(back.may_change_left(at(&prov, -1, 70.0)), Some(true));
    assert_eq!(back.may_change_right(at(&prov, -2, 30.0)), Some(true));
}
