//! Lane visibility: how far a driver can see from each lane, from its
//! `<visibility>`s.
//!
//! `tests/data/lane_visibility.xodr` is generated by `lane_visibility.py`.
//! Its road is a straight along +X, so a lane's distance along its
//! centerline is the road's `s`, less the start of its lane section.

use libopendrive::{
    load_file_with_provenance, load_str_with_provenance, LaneId, Provenance, Visibility, Warning,
};

const FIXTURE: &str = "tests/data/lane_visibility.xodr";

/// The baked lane `od_id` of lane section `section`.
fn lane(prov: &Provenance, section: usize, od_id: i32) -> LaneId {
    prov.lanes
        .iter()
        .find(|p| p.section == section && p.od_id == od_id)
        .unwrap_or_else(|| panic!("section {section} lane {od_id}"))
        .lane
}

fn seen(forward: f32, back: f32, left: f32, right: f32) -> Visibility {
    Visibility {
        forward,
        back,
        left,
        right,
    }
}

#[test]
fn each_visibility_holds_to_the_next_or_the_end_of_its_section() {
    let (net, prov) = load_file_with_provenance(FIXTURE).unwrap();
    let stretches: Vec<_> = net
        .lane_visibility()
        .iter()
        .filter(|a| a.lane == lane(&prov, 0, -1))
        .map(|a| (a.from, a.to, a.value))
        .collect();
    assert_eq!(
        stretches,
        [
            (0.0, 30.0, seen(200.0, 50.0, 3.5, 10.0)),
            (30.0, 60.0, seen(80.0, 50.0, 3.5, 10.0)),
        ]
    );
    let second = lane(&prov, 1, -1);
    assert_eq!(
        net.lane_visibility_at(second, 0.0),
        Some(&seen(300.0, 50.0, 3.5, 10.0))
    );
    assert_eq!(
        net.lane_visibility_at(second, 40.0),
        Some(&seen(300.0, 50.0, 3.5, 10.0))
    );
    assert_eq!(net.lane_visibility_at(lane(&prov, 1, 1), 10.0), None);
}

#[test]
fn a_visibility_with_a_distance_it_cannot_read_is_dropped_with_a_warning() {
    let (net, prov) = load_file_with_provenance(FIXTURE).unwrap();
    let left = lane(&prov, 0, 1);
    let stretches: Vec<_> = net
        .lane_visibility()
        .iter()
        .filter(|a| a.lane == left)
        .map(|a| (a.from, a.to, a.value))
        .collect();
    assert_eq!(stretches, [(0.0, 20.0, seen(120.0, 40.0, 10.0, 3.5))]);
    let dropped: Vec<_> = prov
        .warnings
        .iter()
        .filter(|w| matches!(w, Warning::VisibilityDropped { .. }))
        .cloned()
        .collect();
    assert_eq!(
        dropped,
        [
            Warning::VisibilityDropped {
                road_id: "0".into(),
                s: 20.0,
                lane: 1,
                distance: "left".into(),
                value: String::new(),
            },
            Warning::VisibilityDropped {
                road_id: "0".into(),
                s: 40.0,
                lane: 1,
                distance: "back".into(),
                value: "-5".into(),
            },
        ]
    );
    assert_eq!(
        dropped[1].to_string(),
        "road \"0\": lane 1's <visibility> at s 40.00 m dropped, back \"-5\" is not a distance"
    );
}

#[test]
fn a_distance_too_large_for_f32_is_dropped_with_a_warning() {
    let xml = std::fs::read_to_string(FIXTURE)
        .unwrap()
        .replace(r#"forward="300""#, r#"forward="1e39""#);
    let (net, prov) = load_str_with_provenance(&xml).unwrap();
    assert!(net
        .lane_visibility()
        .iter()
        .all(|a| a.value.forward.is_finite()));
    assert!(prov.warnings.iter().any(|w| matches!(
        w,
        Warning::VisibilityDropped { distance, value, .. } if distance == "forward" && value == "1e39"
    )));
}

#[cfg(feature = "serde")]
#[test]
fn lane_visibility_survives_a_serde_round_trip() {
    let (net, _) = load_file_with_provenance(FIXTURE).unwrap();
    let json = serde_json::to_string(&net).unwrap();
    let back: libopendrive::RoadNetwork = serde_json::from_str(&json).unwrap();
    assert_eq!(back.lane_visibility(), net.lane_visibility());
    assert!(!net.lane_visibility().is_empty());
}
