//! Lane heights: `<lane><height>` raising sidewalks off the road.
//!
//! `tests/data/lane_heights.xodr` is generated by `lane_heights.py`. Every
//! road there is straight or a plain arc, so each raised edge has a closed
//! form to check against.

use xodr::{
    load_file_with_provenance, Lane, LaneProvenance, Mesh, Point, Provenance, RoadNetwork, Shape,
};

const FIXTURE: &str = "tests/data/lane_heights.xodr";

fn fixture() -> (RoadNetwork, Provenance) {
    load_file_with_provenance(FIXTURE).expect("the fixture loads")
}

/// The baked lane `od_id` of lane section `section` on road `road`.
fn lane<'a>(
    net: &'a RoadNetwork,
    prov: &'a Provenance,
    road: &str,
    section: usize,
    od_id: i32,
) -> (&'a Lane, &'a LaneProvenance) {
    let p = prov
        .lanes
        .iter()
        .find(|p| p.road_id == road && p.section == section && p.od_id == od_id)
        .unwrap_or_else(|| panic!("road {road} section {section} lane {od_id}"));
    (net.lane(p.lane).expect("a baked lane"), p)
}

/// The rib pairs of a lane's slice of the mesh, as `(left, right)` looking
/// along its centerline.
fn ribs(mesh: &Mesh, lane: &Lane) -> Vec<(Point, Point)> {
    let span = mesh
        .lanes
        .iter()
        .find(|s| s.lane == lane.id)
        .expect("the lane is in the mesh");
    mesh.vertices[span.vertices.start as usize..span.vertices.end as usize]
        .chunks(2)
        .map(|pair| (pair[0], pair[1]))
        .collect()
}

/// The kerb height of the ramped sidewalk -2 at `s` metres into its lane
/// section: 0.02 m, then up to 0.12 m between 20 m and 21 m.
fn ramp_inner(s: f64) -> f64 {
    0.02 + 0.1 * (s - 20.0).clamp(0.0, 1.0)
}

fn assert_near(got: f64, want: f64, tolerance: f64, what: &str) {
    assert!(
        (got - want).abs() <= tolerance,
        "{what}: got {got}, want {want} within {tolerance}"
    );
}

/// A right lane's left rib is its inner border, and a left lane's its outer
/// one.
#[test]
fn a_sidewalk_stands_at_its_heights_across_and_along() {
    let (net, prov) = fixture();
    let mesh = net.surface_mesh();
    let (right, _) = lane(&net, &prov, "0", 0, -2);
    for (inner, outer) in ribs(&mesh, right) {
        let s = f64::from(inner.x + outer.x) / 2.0;
        assert_near(
            f64::from(inner.z),
            ramp_inner(s),
            1e-4,
            &format!("kerb z at {s}"),
        );
        assert_near(f64::from(outer.z), 0.12, 1e-4, &format!("outer z at {s}"));
        assert_near(f64::from(inner.y), -3.5, 2e-3, &format!("kerb y at {s}"));
        assert_near(f64::from(outer.y), -5.5, 2e-3, &format!("outer y at {s}"));
    }
    let (left, _) = lane(&net, &prov, "0", 0, 2);
    for (outer, inner) in ribs(&mesh, left) {
        assert_near(f64::from(inner.z), 0.12, 1e-6, "left kerb z");
        assert_near(f64::from(outer.z), 0.12, 1e-6, "left outer z");
        assert_near(f64::from(inner.y), 3.5, 1e-5, "left kerb y");
        assert_near(f64::from(outer.y), 5.5, 1e-5, "left outer y");
    }
}

/// The kerb edge of lane -1 and the sidewalk's meet at the same y, 0.02 m
/// apart, and no face joins them.
#[test]
fn the_step_up_to_a_sidewalk_stays_open() {
    let (net, prov) = fixture();
    let mesh = net.surface_mesh();
    for od_id in [1, -1] {
        let (road_lane, _) = lane(&net, &prov, "0", 0, od_id);
        for (a, b) in ribs(&mesh, road_lane) {
            assert_eq!((a.z, b.z), (0.0, 0.0), "lane {od_id} stays on the road");
        }
    }
    let (road_lane, _) = lane(&net, &prov, "0", 0, -1);
    let (sidewalk, _) = lane(&net, &prov, "0", 0, -2);
    let kerb = ribs(&mesh, road_lane)[0].1;
    let top = ribs(&mesh, sidewalk)[0].0;
    assert_near(f64::from(kerb.y), f64::from(top.y), 2e-3, "kerb y");
    assert_near(f64::from(top.z - kerb.z), 0.02, 1e-4, "kerb step");
    let span = |l: &Lane| {
        mesh.lanes
            .iter()
            .find(|s| s.lane == l.id)
            .unwrap()
            .vertices
            .clone()
    };
    let (a, b) = (span(road_lane), span(sidewalk));
    for tri in mesh.indices.chunks(3) {
        let touches = |r: &std::ops::Range<u32>| tri.iter().any(|i| r.contains(i));
        assert!(
            !(touches(&a) && touches(&b)),
            "a face joins lane -1 to the sidewalk"
        );
    }
}

/// The ramp has a station at each end, and the centerline there rises by
/// the height halfway across, `(inner + outer) / 2`.
#[test]
fn a_ramp_bakes_as_long_as_the_file_says() {
    let (net, prov) = fixture();
    let (sidewalk, _) = lane(&net, &prov, "0", 0, -2);
    let at = |x: f32| {
        sidewalk
            .center
            .points()
            .iter()
            .find(|p| (p.x - x).abs() < 1e-4)
            .copied()
            .unwrap_or_else(|| panic!("no station at {x}"))
    };
    assert_near(f64::from(at(20.0).z), 0.07, 1e-6, "ramp foot");
    assert_near(f64::from(at(21.0).z), 0.12, 1e-6, "ramp top");
}

/// Halfway up the ramp the surface is 0.095 m high, midway between a
/// 0.07 m kerb and a 0.12 m outer edge. The ramp's quad is twisted, since
/// its kerb rises and its outer edge does not, so its two triangles cut the
/// corner, by at most a quarter of the 0.1 m rise.
#[test]
fn a_ramp_quad_cuts_the_corner_by_at_most_a_quarter_of_the_rise() {
    let (net, _) = fixture();
    let (z, _) = net
        .surface_mesh()
        .height_at(20.5, -4.5)
        .expect("on the ramp");
    assert_near(f64::from(z), 0.095, 0.025 + 1e-5, "halfway up the ramp");
}

#[test]
fn a_sidewalk_goes_straight_across_from_kerb_to_outer_edge() {
    let (net, _) = fixture();
    let mesh = net.surface_mesh();
    for (t, want) in [(-3.6, 0.025), (-4.5, 0.07), (-5.4, 0.115)] {
        let (z, _) = mesh.height_at(10.0, t).expect("on the sidewalk");
        assert_near(f64::from(z), want, 1e-4, &format!("z at t {t}"));
    }
}

/// Sidewalk -2's outer edge, toward -y, is 0.1 m higher over 2 m, so its
/// surface faces up and toward +y. A positive bank raises the +t edge. Past
/// the ramp the kerb is as high as the outer edge.
#[test]
fn a_sloped_sidewalk_leans_toward_the_road() {
    let (net, prov) = fixture();
    let (sloped, _) = lane(&net, &prov, "0", 0, -2);
    let sample = sloped.sample_at(10.0);
    assert_near(f64::from(sample.bank), -(0.1_f64).atan2(2.0), 1e-6, "bank");
    assert!(sample.up.y > 0.04, "up {:?}", sample.up);
    let flat = lane(&net, &prov, "0", 0, 2).0.sample_at(10.0);
    assert_eq!(flat.bank, 0.0);
    assert_near(
        f64::from(sloped.sample_at(30.0).bank),
        0.0,
        1e-6,
        "bank past the ramp",
    );
}

#[test]
fn provenance_gives_the_heights_at_each_centerline_vertex() {
    let (net, prov) = fixture();
    let (sloped, p) = lane(&net, &prov, "0", 0, -2);
    assert_eq!(p.heights.len(), sloped.center.points().len());
    for (point, h) in sloped.center.points().iter().zip(&p.heights) {
        let s = f64::from(point.x);
        assert_near(
            f64::from(h.inner),
            ramp_inner(s),
            1e-6,
            &format!("inner at {s}"),
        );
        assert_near(f64::from(h.outer), 0.12, 1e-6, &format!("outer at {s}"));
    }
    for od_id in [1, -1] {
        assert!(lane(&net, &prov, "0", 0, od_id).1.heights.is_empty());
    }
}

/// The road's own axes on road 1, which climbs at 3 % and banks at 0.05 rad
/// along +X: along it, across it to the left, and up from it.
fn banked_axes() -> [[f64; 3]; 3] {
    let unit = |v: [f64; 3]| {
        let l = v.iter().map(|c| c * c).sum::<f64>().sqrt();
        v.map(|c| c / l)
    };
    let cross =
        |[a, b, c]: [f64; 3], [x, y, z]: [f64; 3]| [b * z - c * y, c * x - a * z, a * y - b * x];
    let along = unit([1.0, 0.0, 0.03]);
    let up = unit(cross(along, [0.0, 0.05_f64.cos(), 0.05_f64.sin()]));
    [along, cross(up, along), up]
}

/// On road 1, where the road surface is at `(s, t)`.
fn banked_surface(s: f64, t: f64) -> [f64; 3] {
    [s, -40.0 + t * 0.05_f64.cos(), 0.03 * s + t * 0.05_f64.sin()]
}

/// Each edge of a raised lane on a banked, climbing road stands off the
/// road along its normal. The tessellator tilts the lane's cross axis rather
/// than moving each edge to its own height, and the lane's width is the
/// chord across it, so each edge lands on its border. The crate docs bound
/// the rest at 0.05 m times the grade along the road. This measures all
/// three.
#[test]
fn on_a_banked_climbing_road_a_height_stands_off_along_the_normal() {
    let (net, prov) = fixture();
    let mesh = net.surface_mesh();
    let [along, across, up] = banked_axes();
    let dot = |a: [f64; 3], b: [f64; 3]| a.iter().zip(b).map(|(x, y)| x * y).sum::<f64>();
    let (mut worst_along, mut worst_up, mut worst_across) = (0.0_f64, 0.0_f64, 0.0_f64);
    for (od_id, inner_t, outer_t) in [(-2, -3.5, -5.5), (2, 3.5, 5.5)] {
        let (sidewalk, p) = lane(&net, &prov, "1", 0, od_id);
        let pairs = ribs(&mesh, sidewalk);
        assert_eq!(pairs.len(), p.heights.len(), "no station was welded away");
        for ((left, right), h) in pairs.iter().zip(&p.heights) {
            let (inner, outer) = if od_id < 0 {
                (left, right)
            } else {
                (right, left)
            };
            let mid = f64::from(h.inner + h.outer) / 2.0;
            let s = f64::from(inner.x + outer.x) / 2.0 - mid * up[0];
            for (rib, t, height) in [(inner, inner_t, h.inner), (outer, outer_t, h.outer)] {
                let want = banked_surface(s, t);
                let want = [0, 1, 2].map(|k| want[k] + f64::from(height) * up[k]);
                let off = [0, 1, 2].map(|k| f64::from(rib.to_array()[k]) - want[k]);
                worst_along = worst_along.max(dot(off, along).abs());
                worst_up = worst_up.max(dot(off, up).abs());
                worst_across = worst_across.max(dot(off, across).abs());
            }
        }
    }
    assert!(
        worst_along < 0.05 * 0.03 + 1e-5,
        "{worst_along} m off along the road"
    );
    assert!(worst_up < 1e-4, "{worst_up} m off along the normal");
    assert!(worst_across < 1e-4, "{worst_across} m off across");
}

/// Section 1 of road 2 starts at s = 30. Its first height, at sOffset 5,
/// holds before it, and the ramp runs from s = 35 to 37.
#[test]
fn heights_count_from_their_own_lane_section() {
    let (net, prov) = fixture();
    let mesh = net.surface_mesh();
    let (level, p) = lane(&net, &prov, "2", 0, -2);
    assert!(p.heights.is_empty());
    assert!(level.bank.is_empty());
    let (raised, _) = lane(&net, &prov, "2", 1, -2);
    for (inner, outer) in ribs(&mesh, raised) {
        let s = f64::from(inner.x + outer.x) / 2.0;
        let f = ((s - 35.0) / 2.0).clamp(0.0, 1.0);
        assert_near(
            f64::from(inner.z),
            0.15 * f,
            1e-4,
            &format!("kerb z at {s}"),
        );
        assert_near(
            f64::from(outer.z),
            0.1 + 0.05 * f,
            1e-4,
            &format!("outer z at {s}"),
        );
    }
    let xs: Vec<f32> = raised.center.points().iter().map(|p| p.x).collect();
    for knot in [35.0, 37.0] {
        assert!(
            xs.iter().any(|x| (x - knot).abs() < 1e-4),
            "no station at {knot}: {xs:?}"
        );
    }
}

/// Road 3 curves left on a 25 m radius about (0, 105).
#[test]
fn a_sidewalk_on_a_curve_keeps_its_height_and_radius() {
    let (net, prov) = fixture();
    let mesh = net.surface_mesh();
    let radius = |p: Point| f64::from(p.x).hypot(f64::from(p.y) - 105.0);
    for (od_id, left_r, right_r) in [(2, 19.5, 21.5), (-2, 28.5, 30.5)] {
        let (sidewalk, _) = lane(&net, &prov, "3", 0, od_id);
        for (left, right) in ribs(&mesh, sidewalk) {
            assert_near(f64::from(left.z), 0.12, 1e-5, "left z");
            assert_near(f64::from(right.z), 0.12, 1e-5, "right z");
            assert_near(radius(left), left_r, 2e-3, "left radius");
            assert_near(radius(right), right_r, 2e-3, "right radius");
        }
    }
}

#[test]
fn a_map_with_raised_lanes_tessellates_to_a_valid_mesh() {
    let (net, _) = fixture();
    net.surface_mesh().validate().expect("a valid mesh");
}

/// Where a solid object stands: its position, the middle of its base.
fn solid_at(net: &RoadNetwork, prov: &Provenance, od_id: &str) -> Point {
    let p = prov
        .objects
        .iter()
        .find(|p| p.od_id == od_id)
        .unwrap_or_else(|| panic!("object {od_id}"));
    let object = net.objects().iter().find(|o| o.id == p.object).unwrap();
    match object.shape {
        Shape::Solid { position, .. } => position,
        ref other => panic!("object {od_id} is {other:?}"),
    }
}

/// Each pole on road 0 stands on the lane under it: on sidewalk -2 halfway
/// across its slope, and past its ramp at 0.12 m, on sidewalk 2 at 0.12 m,
/// and on lane -1 on the road.
#[test]
fn an_object_on_a_sidewalk_stands_on_it() {
    let (net, prov) = fixture();
    for (od_id, z) in [("1", 0.07), ("2", 0.12), ("3", 0.12), ("4", 0.0)] {
        let at = solid_at(&net, &prov, od_id);
        assert_near(f64::from(at.z), z, 1e-6, &format!("object {od_id} z"));
    }
}

/// The sign on sidewalk 2 stands 2 m above it, and takes effect on it.
#[test]
fn a_sign_on_a_sidewalk_stands_on_it() {
    let (net, _) = fixture();
    let sign = &net.signals()[0];
    assert_near(f64::from(sign.position.z), 2.12, 1e-6, "board z");
    assert_near(f64::from(sign.applies_at[0].z), 0.12, 1e-6, "applies at z");
}

/// Each road mark on road 0 lies in the surface of the lane it belongs to:
/// the center line and the kerbs, the outer borders of lanes 1 and -1, on
/// the road, and the sidewalks' outer marks on the sidewalks. Sidewalk -2
/// rises 0.05 m a metre toward its outer edge until its ramp, so its mark,
/// 0.12 m wide, tilts with it.
#[test]
fn a_road_mark_lies_on_the_lane_it_belongs_to() {
    let (net, prov) = fixture();
    let marks: Vec<_> = prov
        .road_marks
        .iter()
        .filter(|p| p.road_id == "0")
        .collect();
    assert_eq!(marks.len(), 5);
    for p in marks {
        let mark = net
            .road_marks()
            .iter()
            .find(|m| m.id == p.road_mark)
            .unwrap();
        for corner in mark.lines.iter().flat_map(|l| &l.pieces).flatten() {
            let (x, y) = (f64::from(corner.x), f64::from(corner.y));
            let want = match p.od_lane_id {
                -1..=1 => 0.0,
                2 => 0.12,
                -2 if x >= 21.0 => 0.12,
                -2 => ramp_inner(x) + (0.12 - ramp_inner(x)) * (-y - 3.5) / 2.0,
                other => panic!("lane {other}"),
            };
            let what = format!("lane {} mark z at ({x}, {y})", p.od_lane_id);
            assert_near(f64::from(corner.z), want, 1e-6, &what);
        }
    }
}
