//! Lateral shapes: `<lateralProfile><shape>` giving a road's cross-section.
//!
//! `tests/data/lateral_shapes.xodr` is generated by `lateral_shapes.py`.
//! Every road there is a straight along +X, so each border's height has a
//! closed form to check against.

use libopendrive::{
    load_file_with_provenance, Lane, LaneProvenance, Mesh, Point, Provenance, RoadNetwork, Warning,
};

const FIXTURE: &str = "tests/data/lateral_shapes.xodr";

/// Where each road's reference line runs, as `y`.
const ROAD_Y: [f64; 5] = [0.0, 30.0, 60.0, 90.0, 120.0];

/// The parabolic crown's `k`, in `h = -k t^2`.
const K: f64 = 0.175 / 49.0;

fn fixture() -> (RoadNetwork, Provenance) {
    load_file_with_provenance(FIXTURE).expect("the fixture loads")
}

fn lane<'a>(
    net: &'a RoadNetwork,
    prov: &'a Provenance,
    road: usize,
    od_id: i32,
) -> (&'a Lane, &'a LaneProvenance) {
    let p = prov
        .lanes
        .iter()
        .find(|p| p.road_id == road.to_string() && p.od_id == od_id)
        .unwrap_or_else(|| panic!("road {road} lane {od_id}"));
    (net.lane(p.lane).expect("a baked lane"), p)
}

/// The rib pairs of a lane's slice of the mesh, as `(left, right)` looking
/// along +s, where every lane here runs.
fn ribs(mesh: &Mesh, lane: &Lane) -> Vec<(Point, Point)> {
    let span = mesh
        .lanes
        .iter()
        .find(|s| s.lane == lane.id)
        .expect("the lane is in the mesh");
    mesh.vertices[span.vertices.start as usize..span.vertices.end as usize]
        .chunks(2)
        .map(|pair| (pair[0], pair[1]))
        .collect()
}

fn assert_near(got: f32, want: f64, tolerance: f64, what: &str) {
    let got = f64::from(got);
    assert!(
        (got - want).abs() <= tolerance,
        "{what}: got {got}, want {want} within {tolerance}"
    );
}

/// Each lane of the four-lane roads with the `t` of its left and right
/// border, looking along +s.
const FOUR_LANES: [(i32, f64, f64); 4] = [
    (2, 7.0, 3.5),
    (1, 3.5, 0.0),
    (-1, 0.0, -3.5),
    (-2, -3.5, -7.0),
];

fn crown(t: f64) -> f64 {
    -0.025 * t.abs()
}

/// The parabolic crown of road 1 at `(s, t)`, flattening to 0 at s = 50.
fn parabola(s: f64, t: f64) -> f64 {
    -K * t * t * (1.0 - s / 50.0).max(0.0)
}

#[test]
fn a_crown_stands_at_its_shape_on_every_border() {
    let (net, prov) = fixture();
    let mesh = net.surface_mesh();
    for (od_id, left_t, right_t) in FOUR_LANES {
        for (left, right) in ribs(&mesh, lane(&net, &prov, 0, od_id).0) {
            let what = format!("lane {od_id} at s {}", left.x);
            assert_near(left.z, crown(left_t), 1e-4, &what);
            assert_near(right.z, crown(right_t), 1e-4, &what);
        }
    }
}

#[test]
fn border_heights_go_linearly_along_s_between_profiles() {
    let (net, prov) = fixture();
    let mesh = net.surface_mesh();
    let mut past_the_last = 0;
    for (od_id, left_t, right_t) in FOUR_LANES {
        for (left, right) in ribs(&mesh, lane(&net, &prov, 1, od_id).0) {
            let s = f64::from(left.x);
            let what = format!("lane {od_id} at s {s}");
            assert_near(left.z, parabola(s, left_t), 1e-4, &what);
            assert_near(right.z, parabola(s, right_t), 1e-4, &what);
            past_the_last += usize::from(s > 50.0);
        }
    }
    assert!(past_the_last > 0, "no rib after the last profile");
}

#[test]
fn a_profile_s_is_a_station() {
    let (net, prov) = fixture();
    let points = lane(&net, &prov, 1, -1).0.center.points();
    assert!(points.iter().any(|p| (p.x - 50.0).abs() < 1e-4));
}

#[test]
fn mid_lane_the_mesh_sags_under_a_curved_shape_by_a_quarter_of_c_w_squared() {
    let (net, prov) = fixture();
    for p in lane(&net, &prov, 1, -1).0.center.points() {
        let s = f64::from(p.x);
        let sag = K * 3.5 * 3.5 / 4.0 * (1.0 - s / 50.0).max(0.0);
        assert_near(p.z, parabola(s, -1.75) - sag, 1e-4, &format!("s {s}"));
    }
}

#[test]
fn a_shape_on_a_banked_road_stands_off_the_tilted_plane() {
    let (net, prov) = fixture();
    let mesh = net.surface_mesh();
    let (sin, cos) = 0.05_f64.sin_cos();
    for (od_id, left_t, right_t) in FOUR_LANES {
        for (left, right) in ribs(&mesh, lane(&net, &prov, 2, od_id).0) {
            for (rib, t) in [(left, left_t), (right, right_t)] {
                let h = crown(t);
                let what = format!("lane {od_id} at t {t}, s {}", rib.x);
                assert_near(rib.z, t * sin + h * cos, 1e-4, &what);
                assert_near(rib.y, ROAD_Y[2] + t * cos - h * sin, 2e-3, &what);
            }
        }
    }
}

#[test]
fn a_sidewalk_on_a_crown_stands_its_height_off_the_crown() {
    let (net, prov) = fixture();
    let mesh = net.surface_mesh();
    let (sidewalk, p) = lane(&net, &prov, 3, -2);
    for (inner, outer) in ribs(&mesh, sidewalk) {
        assert_near(inner.z, crown(3.5) + 0.12, 1e-4, "kerb");
        assert_near(outer.z, crown(5.5) + 0.12, 1e-4, "outer edge");
    }
    assert!(p.heights.iter().all(|h| h.inner == 0.12 && h.outer == 0.12));
    assert!(lane(&net, &prov, 3, -1).1.heights.is_empty());
}

/// Neighbouring lanes share a border height. A tilted lane's edge falls
/// `w / 2 * (1 - cos α)` short of its border in plan, 0.55 mm on a 3.5 m
/// lane at 2.5 % and 1.23 mm at 3.75 %, so two edges part by the sum.
#[test]
fn neighbouring_lanes_meet_at_the_same_height() {
    let (net, prov) = fixture();
    let mesh = net.surface_mesh();
    for road in [0, 1, 2] {
        for pair in FOUR_LANES.windows(2) {
            let outer = ribs(&mesh, lane(&net, &prov, road, pair[0].0).0);
            let inner = ribs(&mesh, lane(&net, &prov, road, pair[1].0).0);
            assert_eq!(outer.len(), inner.len());
            for ((_, a), (b, _)) in outer.iter().zip(&inner) {
                let what = format!("road {road}: lanes {} and {}", pair[0].0, pair[1].0);
                assert!((a.z - b.z).abs() < 1e-4, "{what} part at {a:?} and {b:?}");
                assert!(
                    (*a - *b).length() < 1.5e-3,
                    "{what} part at {a:?} and {b:?}"
                );
            }
        }
    }
}

#[test]
fn a_profile_short_of_the_road_holds_its_first_shape_and_warns() {
    let (net, prov) = fixture();
    let mesh = net.surface_mesh();
    for (left, right) in ribs(&mesh, lane(&net, &prov, 4, -1).0) {
        assert_near(left.z, 0.1, 1e-4, "inner");
        assert_near(right.z, 0.1, 1e-4, "outer");
    }
    assert_eq!(
        prov.warnings,
        [Warning::ShapeShortOfRoad {
            road_id: "4".into(),
            s: 0.0
        }]
    );
}

#[test]
fn a_shaped_map_tessellates_to_a_valid_mesh() {
    let (net, _) = fixture();
    net.surface_mesh().validate().expect("a valid mesh");
}
