//! Level lanes: `<lane level="true">`, kept out of the superelevation and
//! the lateral shape.
//!
//! `tests/data/level_lanes.xodr` is generated by `level_lanes.py`. Every
//! road there is a straight along +X on flat ground, so a point's height is
//! what the cross-section gives it.

use xodr::{load_file_with_provenance, Lane, Provenance, RoadNetwork, Shape, Warning};

const FIXTURE: &str = "tests/data/level_lanes.xodr";

/// The superelevation of roads 0 and 2.
const PHI: f32 = 0.05;

fn fixture() -> (RoadNetwork, Provenance) {
    load_file_with_provenance(FIXTURE).expect("the fixture loads")
}

fn lane<'a>(net: &'a RoadNetwork, prov: &Provenance, road: &str, od_id: i32) -> &'a Lane {
    let p = prov
        .lanes
        .iter()
        .find(|p| p.road_id == road && p.od_id == od_id)
        .unwrap_or_else(|| panic!("road {road} lane {od_id}"));
    net.lane(p.lane).expect("a baked lane")
}

/// The height of `lane`'s centerline halfway along.
fn z(lane: &Lane) -> f32 {
    lane.center.point_at(25.0).z
}

fn close(a: f32, b: f32) -> bool {
    (a - b).abs() < 1e-4
}

#[test]
fn a_level_lane_is_flat_at_its_inner_neighbours_outer_border() {
    let (net, prov) = fixture();
    let shoulder = lane(&net, &prov, "0", -2);
    assert!(
        close(shoulder.bank_at(25.0), 0.0),
        "{}",
        shoulder.bank_at(25.0)
    );
    let edge = -3.5 * PHI.sin();
    assert!(close(z(shoulder), edge), "{} != {edge}", z(shoulder));
    let left = lane(&net, &prov, "0", 2);
    assert!(close(left.bank_at(25.0), 0.0));
    assert!(close(z(left), -edge), "{} != {}", z(left), -edge);
}

#[test]
fn the_lane_inside_a_level_lane_keeps_the_superelevation() {
    let (net, prov) = fixture();
    let driving = lane(&net, &prov, "0", -1);
    assert!(close(driving.bank_at(25.0), PHI));
    assert!(close(z(driving), -1.75 * PHI.sin()));
}

#[test]
fn a_level_lane_outside_a_level_lane_stacks_its_height_on_it() {
    let (net, prov) = fixture();
    let sidewalk = lane(&net, &prov, "0", -3);
    assert!(close(sidewalk.bank_at(25.0), 0.0));
    let want = -3.5 * PHI.sin() + 0.12 * PHI.cos();
    assert!(close(z(sidewalk), want), "{} != {want}", z(sidewalk));
}

#[test]
fn a_level_lane_is_kept_out_of_the_lateral_shape() {
    let (net, prov) = fixture();
    let shoulder = lane(&net, &prov, "1", -2);
    assert!(close(shoulder.bank_at(25.0), 0.0));
    assert!(close(z(shoulder), -0.025 * 3.5), "{}", z(shoulder));
}

#[test]
fn a_lane_outside_a_level_lane_is_held_level_with_a_warning() {
    let (net, prov) = fixture();
    let shoulder = lane(&net, &prov, "2", -2);
    assert!(close(shoulder.bank_at(25.0), 0.0));
    assert!(close(lane(&net, &prov, "2", -1).bank_at(25.0), 0.0));
    assert_eq!(
        prov.warnings,
        vec![Warning::LaneNotLevel {
            road_id: "2".into(),
            section: 0,
            lane: -2,
        }]
    );
}

#[test]
fn an_object_on_a_level_lane_stands_on_it() {
    let (net, _) = fixture();
    let Shape::Solid { position, .. } = net.objects()[0].shape else {
        panic!("a solid pole");
    };
    let edge = -3.5 * PHI.sin();
    assert!(close(position.z, edge), "{} != {edge}", position.z);
}

#[test]
fn an_object_on_a_level_lane_with_no_height_stands_on_it() {
    let (net, _) = fixture();
    let Shape::Solid { position, .. } = net.objects()[1].shape else {
        panic!("a solid pole");
    };
    assert!(close(position.z, 0.0), "{} != 0", position.z);
}

#[test]
fn level_lanes_leave_the_mesh_closed() {
    let (net, _) = fixture();
    net.surface_mesh().validate().expect("a valid mesh");
}
