//! Lanes the file links that don't meet, and roads whose `length` is not
//! their reference line's.
//!
//! `tests/data/link_gaps.xodr` is generated by `link_gaps.py`.

use libopendrive::{load_file_with_provenance, Warning};

const FIXTURE: &str = "tests/data/link_gaps.xodr";

fn warnings() -> Vec<Warning> {
    load_file_with_provenance(FIXTURE).unwrap().1.warnings
}

#[test]
fn a_link_across_a_gap_warns_and_is_kept() {
    let gaps: Vec<_> = warnings()
        .into_iter()
        .filter(|w| matches!(w, Warning::LinkGap { .. }))
        .collect();
    let [Warning::LinkGap {
        road_id,
        section,
        lane,
        to_road_id,
        to_section,
        to_lane,
        gap,
    }] = &gaps[..]
    else {
        panic!("one gap, not {gaps:?}");
    };
    assert_eq!((road_id.as_str(), *section, *lane), ("2", 0, -1));
    assert_eq!((to_road_id.as_str(), *to_section, *to_lane), ("3", 0, -1));
    assert!((gap - 2.0).abs() < 1e-3, "{gap}");
    assert_eq!(
        gaps[0].to_string(),
        "road \"2\", lane section 0: lane -1 links to road \"3\", lane section 0, lane -1, 2.00 m away"
    );
    let (net, prov) = load_file_with_provenance(FIXTURE).unwrap();
    let from = prov.lanes.iter().find(|p| p.road_id == "2").unwrap().lane;
    assert_eq!(net.lane(from).unwrap().successors.len(), 1);
}

#[test]
fn a_lane_narrowing_onto_half_a_split_or_handing_over_to_one_opening_beside_it_meets_it() {
    let (net, prov) = load_file_with_provenance(FIXTURE).unwrap();
    let lane = |road: &str, section: usize, od_id: i32| {
        let id = prov
            .lanes
            .iter()
            .find(|p| p.road_id == road && p.section == section && p.od_id == od_id)
            .unwrap()
            .lane;
        net.lane(id).unwrap()
    };
    assert_eq!(lane("0", 0, -1).successors, [lane("0", 1, -1).id]);
    assert_eq!(lane("0", 1, -2).successors, [lane("1", 0, -3).id]);
    assert!(!warnings().iter().any(
        |w| matches!(w, Warning::LinkGap { road_id, .. } if road_id == "0" || road_id == "1")
    ));
}

#[test]
fn a_road_whose_length_is_not_its_reference_lines_warns() {
    let lengths: Vec<_> = warnings()
        .into_iter()
        .filter(|w| matches!(w, Warning::RoadLengthMismatch { .. }))
        .collect();
    assert_eq!(
        lengths,
        [Warning::RoadLengthMismatch {
            road_id: "1".into(),
            length: 30.0,
            plan_view: 40.0,
        }]
    );
    assert_eq!(
        lengths[0].to_string(),
        "road \"1\": length 30.000 m, but its <planView> ends at 40.000 m"
    );
}
