//! Objects placed along a road land where the road says they are.
//!
//! `objects.xodr` is generated by `scenariogeneration` (see `objects.py`), so
//! the file comes from a writer other than this crate. Its road 0 is a 100 m
//! arc of curvature 0.005 from the origin heading +X, at elevation
//! `1 + 0.02 s`, and carries the objects. Its road 1 is a flat 60 m straight
//! from `(0, -40)` heading +X, and places some of them again with
//! `<objectReference>`s. That puts every expected placement in closed form.

use libopendrive::{
    load_file, load_file_with_provenance, Corner, Extent, Marking, Material, Object, ObjectId,
    ObjectType, Orientation, ParkingSpace, Point, Section, Shape, UserData, Vector,
};

const OBJECTS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/objects.xodr");
const E6MINI: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/e6mini.xodr");

const CURVATURE: f64 = 0.005;

/// The road surface at `(s, t)`, and the reference line's heading there.
fn on_road(s: f64, t: f64) -> (Point, f64) {
    let hdg = CURVATURE * s;
    let x = hdg.sin() / CURVATURE - t * hdg.sin();
    let y = (1.0 - hdg.cos()) / CURVATURE + t * hdg.cos();
    let z = 1.0 + 0.02 * s;
    (Point::new(x as f32, y as f32, z as f32), hdg)
}

/// Road 1's surface at `(s, t)`. Its heading is 0 everywhere.
fn on_straight(s: f64, t: f64) -> Point {
    Point::new(s as f32, (t - 40.0) as f32, 0.0)
}

/// `on_road(s, t)` raised by `dz`.
fn raised(s: f64, t: f64, dz: f64) -> Point {
    let (mut p, _) = on_road(s, t);
    p.z += dz as f32;
    p
}

fn assert_near(got: Point, want: Point, what: &str) {
    assert!(
        (got - want).length() < 1e-3,
        "{what}: got {got:?}, expected {want:?}"
    );
}

/// A corner whose base is `base` and whose top is `height` straight above it.
fn assert_corner(got: &Corner, base: Point, height: f32, what: &str) {
    assert_near(got.base, base, &format!("{what} base"));
    assert_near(
        got.top,
        Point::new(base.x, base.y, base.z + height),
        &format!("{what} top"),
    );
}

/// `[u, v, z]` turned roll about X, then pitch about Y, then yaw about Z.
fn turned((yaw, pitch, roll): (f64, f64, f64), [u, v, z]: [f32; 3]) -> Vector {
    let [u, v, z] = [u, v, z].map(f64::from);
    let (sr, cr) = roll.sin_cos();
    let (sp, cp) = pitch.sin_cos();
    let (sy, cy) = yaw.sin_cos();
    let (v, z) = (v * cr - z * sr, v * sr + z * cr);
    let (u, z) = (u * cp + z * sp, -u * sp + z * cp);
    let (u, v) = (u * cy - v * sy, u * sy + v * cy);
    Vector::new(u as f32, v as f32, z as f32)
}

/// Road 0's own axes at `s`: along it up its 2 % grade, level across it, and
/// square to both.
fn road_axes(s: f64) -> [Vector; 3] {
    let (sin, cos) = (CURVATURE * s).sin_cos();
    let along = Vector::new(cos as f32, sin as f32, 0.02).normalize_or_zero();
    let across = Vector::new(-sin as f32, cos as f32, 0.0);
    [along, across, along.cross(across)]
}

/// Where `local` lands in the frame of an object on road 0 at `(s, t)`,
/// raised `z_offset` square to the road and turned `(hdg, pitch, roll)`
/// against its axes.
fn placed(s: f64, t: f64, z_offset: f64, turn: (f64, f64, f64), local: [f32; 3]) -> Point {
    let [along, across, up] = road_axes(s);
    let d = turned(turn, local);
    raised(s, t, 0.0) + up * z_offset as f32 + along * d.x + across * d.y + up * d.z
}

/// The solid's extent, after checking it sits at `(s, t)` raised by
/// `z_offset`, turned `turn` against the road, which tilts it with the grade.
fn assert_solid(
    object: &Object,
    s: f64,
    t: f64,
    z_offset: f64,
    turn: (f64, f64, f64),
) -> Option<Extent> {
    let Shape::Solid {
        position,
        heading,
        pitch,
        roll,
        extent,
    } = object.shape
    else {
        panic!("{} is not a solid: {:?}", object.kind, object.shape);
    };
    let what = format!("{} at s={s}", object.kind);
    let origin = placed(s, t, z_offset, turn, [0.0; 3]);
    assert_near(position, origin, &what);
    let angles = (f64::from(heading), f64::from(pitch), f64::from(roll));
    for axis in [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]] {
        let want = placed(s, t, z_offset, turn, axis) - origin;
        let got = turned(angles, axis);
        assert!(
            (got - want).length() < 1e-5,
            "{what}: axis {axis:?} {got:?}, expected {want:?}"
        );
    }
    extent
}

/// A `<cornerLocal>` at `(u, v)`, `height` tall, of an object on road 0 at
/// `(s, t)` raised `z_offset` and turned `turn`. Its top is up in the
/// object's frame.
fn assert_local_corner(
    got: &Corner,
    (s, t, z_offset, turn): (f64, f64, f64, (f64, f64, f64)),
    (u, v): (f32, f32),
    height: f32,
    what: &str,
) {
    let at = |z| placed(s, t, z_offset, turn, [u, v, z]);
    assert_near(got.base, at(0.0), &format!("{what} base"));
    assert_near(got.top, at(height), &format!("{what} top"));
}

/// The objects baked on `road`.
fn on(road: &str) -> Vec<Object> {
    let (net, prov) = load_file_with_provenance(OBJECTS).expect("objects.xodr loads");
    net.objects()
        .iter()
        .zip(&prov.objects)
        .filter(|(_, p)| p.road_id == road)
        .map(|(o, _)| o.clone())
        .collect()
}

/// Road 0's objects, the ones its `<object>`s place.
fn objects() -> Vec<Object> {
    on("0")
}

fn of_kind(kind: ObjectType) -> Vec<Object> {
    objects().into_iter().filter(|o| o.kind == kind).collect()
}

#[test]
fn single_objects_sit_on_the_road_surface_at_their_station() {
    let objects = objects();

    let shed = &objects[0];
    assert_eq!(shed.kind, ObjectType::Building);
    assert_eq!(shed.name, "Shed");
    let extent = assert_solid(shed, 40.0, -6.0, 0.5, (0.3, 0.0, 0.0));
    assert_eq!(
        extent,
        Some(Extent::Box {
            length: 8.0,
            width: 4.0,
            height: 3.0
        })
    );

    let tree = &objects[1];
    assert_eq!(tree.kind, ObjectType::Tree);
    assert_eq!(tree.name, "");
    let extent = assert_solid(tree, 60.0, 5.0, 0.0, (0.0, 0.1, -0.2));
    assert_eq!(
        extent,
        Some(Extent::Cylinder {
            radius: 1.5,
            height: 7.0
        })
    );

    let marker = &objects[2];
    assert_eq!(marker.kind, ObjectType::None);
    let extent = assert_solid(marker, 10.0, 0.0, 0.0, (0.0, 0.0, 0.0));
    assert_eq!(extent, None);

    // A vendor's own type is still an object, and a height alone still
    // makes a box, one with no footprint.
    let post = &objects[3];
    assert_eq!(post.kind, ObjectType::Unknown);
    let extent = assert_solid(post, 20.0, 4.0, 0.0, (0.0, 0.0, 0.0));
    assert_eq!(
        extent,
        Some(Extent::Box {
            length: 0.0,
            width: 0.0,
            height: 1.2
        })
    );
}

#[test]
fn an_object_keeps_its_subtype_and_whether_it_moves() {
    let objects = objects();
    let (shed, gate) = (&objects[0], &objects[4]);
    assert_eq!((shed.subtype.as_str(), shed.dynamic), ("garage", false));
    assert_eq!(
        (gate.name.as_str(), gate.subtype.as_str()),
        ("Gate", "boom")
    );
    assert!(gate.dynamic);
    // scenariogeneration writes the absence of a subtype as the text "None",
    // and the crate keeps the file's text.
    assert_eq!(objects[1].subtype, "None");
}

#[test]
fn every_object_is_found_by_its_id() {
    let net = load_file(OBJECTS).expect("objects.xodr loads");
    for object in net.objects() {
        assert_eq!(net.object(object.id), Some(object));
    }
    assert_eq!(net.object(ObjectId(net.objects().len())), None);
}

#[test]
fn provenance_names_each_objects_road_od_id_and_station() {
    let (net, prov) = load_file_with_provenance(OBJECTS).expect("objects.xodr loads");
    let prov = prov.objects;
    assert_eq!(prov.len(), net.objects().len(), "one record per object");
    for (object, p) in net.objects().iter().zip(&prov) {
        assert_eq!(p.object, object.id);
    }
    let prov: Vec<_> = prov.into_iter().filter(|p| p.road_id == "0").collect();
    assert!(prov.iter().all(|p| p.referenced_from.is_none()));

    let shed = &prov[0];
    assert_eq!((shed.od_id.as_str(), shed.s, shed.t), ("1", 40.0, -6.0));
    assert_eq!(shed.orientation, Orientation::Positive);
    assert_eq!(shed.valid_length, Some(8.0));
    let gate = &prov[4];
    assert_eq!(
        (gate.od_id.as_str(), gate.orientation),
        ("10", Orientation::Negative)
    );
    assert_eq!(gate.valid_length, None);
    assert_eq!(
        prov[1].orientation,
        Orientation::Both,
        "orientation=\"none\""
    );

    // Every pole a repeat bakes shares its <object>'s id and has its own
    // station.
    let poles: Vec<_> = net
        .objects()
        .iter()
        .zip(&prov)
        .filter(|(o, _)| o.kind == ObjectType::Pole)
        .map(|(_, p)| p)
        .collect();
    assert!(poles.iter().all(|p| p.od_id == "5"));
    let stations: Vec<f64> = poles.iter().map(|p| p.s).collect();
    assert_eq!(
        stations,
        (0..9).map(|k| 5.0 + 10.0 * k as f64).collect::<Vec<_>>()
    );

    // A sweep is anchored where its part on the road starts, and an outline
    // at its <object>.
    let at = |od_id: &str| prov.iter().find(|p| p.od_id == od_id).expect(od_id);
    assert_eq!((at("7").s, at("7").t), (70.0, -8.0));
    assert_eq!((at("8").s, at("8").t), (30.0, 10.0));
}

#[test]
fn a_repeat_becomes_one_object_per_step_with_its_values_interpolated() {
    let poles = of_kind(ObjectType::Pole);
    // s = 5, 15, ..., 85: nine steps of 10 m over 80 m, both ends included.
    assert_eq!(poles.len(), 9);
    for (k, pole) in poles.iter().enumerate() {
        let f = k as f64 / 8.0;
        let s = 5.0 + 10.0 * k as f64;
        let extent = assert_solid(pole, s, -4.0 - 2.0 * f, 0.0, (0.0, 0.0, 0.0));
        assert_eq!(
            extent,
            Some(Extent::Cylinder {
                radius: 0.1,
                height: (1.0 + f) as f32
            })
        );
    }
}

fn sections(object: &Object) -> &[Section] {
    let Shape::Sweep { sections, round } = &object.shape else {
        panic!("{} is not a sweep: {:?}", object.kind, object.shape);
    };
    assert_eq!(*round, object.name == "Pipe", "{} round", object.name);
    sections
}

#[test]
fn a_continuous_repeat_with_a_radius_is_a_pipe() {
    let pipe = objects()
        .into_iter()
        .find(|o| o.name == "Pipe")
        .expect("the pipe");
    // s = 5..45, each section the square round the pipe there. The radius
    // makes it round, and the height given plays no part.
    let sections = sections(&pipe);
    assert_follows_road(sections, 5.0, 45.0);
    for section in sections {
        let s = station(section.left.base);
        let r = 0.3 + 0.2 * (s - 5.0) / 40.0;
        let height = 2.0 * r as f32;
        assert_corner(&section.left, raised(s, -16.0 + r, 0.0), height, "left");
        assert_corner(&section.right, raised(s, -16.0 - r, 0.0), height, "right");
    }
}

/// The `s` of a point on road 0 at any `t`, from its angle round the arc's
/// centre.
fn station(p: Point) -> f64 {
    f64::from(p.x).atan2(1.0 / CURVATURE - f64::from(p.y)) / CURVATURE
}

/// The sections run from `from` to `to`, and the walls between them stray
/// under 1 cm from the road they follow.
fn assert_follows_road(sections: &[Section], from: f64, to: f64) {
    let ends = |section: Option<&Section>| station(section.unwrap().left.base);
    assert!((ends(sections.first()) - from).abs() < 1e-3);
    assert!((ends(sections.last()) - to).abs() < 1e-3);
    for pair in sections.windows(2) {
        let (a, b) = (pair[0].left.base, pair[1].left.base);
        let (sa, sb) = (station(a), station(b));
        assert!(sb > sa, "in order along the road");
        // How far inside the arc through its ends, in plan, the middle of
        // the wall is.
        let from_centre = |p: Point| (p.x as f64).hypot(1.0 / CURVATURE - p.y as f64);
        let strays = from_centre(a) - from_centre(a.lerp(b, 0.5));
        assert!(strays < 0.011, "s={sa}..{sb} strays {strays} m");
    }
}

#[test]
fn a_continuous_repeat_with_no_width_is_a_wall_along_the_road() {
    let railings = of_kind(ObjectType::Railing);
    assert_eq!(railings.len(), 1);
    let sections = sections(&railings[0]);
    assert_follows_road(sections, 0.0, 100.0);
    for section in sections {
        let s = station(section.left.base);
        assert_eq!(section.left, section.right, "no width at s={s}");
        assert_corner(&section.left, raised(s, 7.0, 0.0), 0.8, &format!("s={s}"));
    }
}

#[test]
fn a_continuous_repeat_interpolates_its_cross_section_and_stops_at_the_road_end() {
    let barrier = of_kind(ObjectType::Barrier)
        .into_iter()
        .find(|o| matches!(o.shape, Shape::Sweep { .. }))
        .expect("the barrier sweep");
    let sections = sections(&barrier);
    // The repeat covers s = 70..110 on a 100 m road.
    assert_follows_road(sections, 70.0, 100.0);
    for section in sections {
        let s = station(section.left.base);
        let f = (s - 70.0) / 40.0;
        let (t, half, z) = (-8.0 - f, (0.5 + 0.5 * f) / 2.0, 0.4 * f);
        assert_corner(
            &section.left,
            raised(s, t + half, z),
            1.0,
            &format!("left s={s}"),
        );
        assert_corner(
            &section.right,
            raised(s, t - half, z),
            1.0,
            &format!("right s={s}"),
        );
    }
}

fn outline(object: &Object) -> (&[Corner], bool) {
    let Shape::Outline {
        corners,
        closed,
        holes,
    } = &object.shape
    else {
        panic!("{} is not an outline: {:?}", object.kind, object.shape);
    };
    if object.name != "Courtyard" {
        assert!(holes.is_empty(), "{} has holes", object.name);
    }
    (corners, *closed)
}

#[test]
fn an_inner_outline_is_a_hole_in_the_outline_round_it() {
    let courtyard: Vec<Object> = objects()
        .into_iter()
        .filter(|o| o.name == "Courtyard")
        .collect();
    let [courtyard] = &courtyard[..] else {
        panic!("one object for both outlines: {courtyard:?}");
    };
    let Shape::Outline {
        corners,
        closed: true,
        holes,
    } = &courtyard.shape
    else {
        panic!("a closed outline: {:?}", courtyard.shape);
    };
    let frame = (78.0, 10.0, 0.0, (0.0, 0.0, 0.0));
    let at = |(u, v)| placed(78.0, 10.0, 0.0, frame.3, [u, v, 0.0]);
    for (corner, uv) in corners
        .iter()
        .zip([(0.0, 0.0), (10.0, 0.0), (10.0, 8.0), (0.0, 8.0)])
    {
        assert_local_corner(corner, frame, uv, 4.0, &format!("outer {uv:?}"));
    }
    let [hole] = &holes[..] else {
        panic!("one hole: {holes:?}");
    };
    let well = [(3.0, 2.0), (7.0, 2.0), (7.0, 5.0), (3.0, 5.0)];
    assert_eq!(hole.len(), 4);
    for (corner, uv) in hole.iter().zip(well) {
        assert_local_corner(corner, frame, uv, 4.0, &format!("hole {uv:?}"));
    }

    // The border naming the hole runs round it.
    let [curb] = &courtyard.borders[..] else {
        panic!("one border: {:?}", courtyard.borders);
    };
    assert_eq!(curb.pieces.len(), 4);
    for (k, piece) in curb.pieces.iter().enumerate() {
        let (from, to) = (at(well[k]), at(well[(k + 1) % 4]));
        assert_piece(piece, from, to, 0.2, &format!("curb {k}"));
    }
}

#[test]
fn a_local_outline_is_placed_in_the_objects_own_frame() {
    let house = objects()
        .into_iter()
        .find(|o| o.name == "House")
        .expect("the house");
    let (corners, closed) = outline(&house);
    assert!(closed);
    // The frame's origin is the object's station raised by its zOffset, and
    // it is turned by the object's hdg against the road's own axes.
    for (corner, uv) in corners
        .iter()
        .zip([(0.0, 0.0), (6.0, 0.0), (6.0, 4.0), (0.0, 4.0)])
    {
        let frame = (30.0, 10.0, 0.1, (0.2, 0.0, 0.0));
        assert_local_corner(corner, frame, uv, 5.0, &format!("house {uv:?}"));
    }
    assert_eq!(corners.len(), 4);
}

#[test]
fn a_road_outline_follows_the_road_and_stays_open() {
    let fence = objects()
        .into_iter()
        .find(|o| o.name == "Fence")
        .expect("the fence");
    let (corners, closed) = outline(&fence);
    assert!(!closed);
    assert_eq!(corners.len(), 3);
    for (corner, (s, t)) in corners
        .iter()
        .zip([(50.0, -12.0), (60.0, -12.0), (60.0, -14.0)])
    {
        assert_corner(corner, raised(s, t, 0.0), 1.5, &format!("fence ({s}, {t})"));
    }
}

#[test]
fn an_outlined_object_has_no_solid_of_its_own() {
    let solids = objects()
        .into_iter()
        .filter(|o| matches!(o.shape, Shape::Solid { .. }))
        .count();
    // Shed, tree, marker, guide post, gate, nine poles. The outlined house
    // and fence, and the swept railing and barrier, add no solid.
    // Plus two sweeps, and the house, fence, crosswalk and island outlines.
    // The two parking bays are solids too, the courtyard and the board
    // outlines, and the pipe a sweep.
    assert_eq!(solids, 5 + 9 + 2);
    assert_eq!(objects().len(), 5 + 9 + 2 + 4 + 2 + 2 + 1);
}

#[test]
fn a_reference_places_the_object_it_names_at_its_own_station() {
    let shed = &on("1")[0];
    assert_eq!(
        (shed.kind, shed.name.as_str(), shed.subtype.as_str()),
        (ObjectType::Building, "Shed", "garage")
    );
    let Shape::Solid {
        position,
        heading,
        extent,
        ..
    } = shed.shape
    else {
        panic!("the shed is not a solid: {:?}", shed.shape);
    };
    // The reference's s, t and zOffset, on road 1, turned by the object's own
    // hdg against a road heading of 0.
    assert_near(position, on_straight(10.0, -5.0) + Vector::Z * 0.2, "shed");
    assert!((heading - 0.3).abs() < 1e-6, "heading {heading}");
    assert_eq!(
        extent,
        Some(Extent::Box {
            length: 8.0,
            width: 4.0,
            height: 3.0
        })
    );
}

#[test]
fn a_referenced_objects_provenance_is_the_references() {
    let (net, prov) = load_file_with_provenance(OBJECTS).expect("objects.xodr loads");
    let referenced: Vec<_> = prov.objects.iter().filter(|p| p.road_id == "1").collect();
    assert!(referenced
        .iter()
        .all(|p| p.referenced_from.as_deref() == Some("0")));

    let shed = referenced[0];
    assert_eq!((shed.od_id.as_str(), shed.s, shed.t), ("1", 10.0, -5.0));
    // Its own orientation and validLength, not the <object>'s "+" and 8.
    assert_eq!(shed.orientation, Orientation::Negative);
    assert_eq!(shed.valid_length, Some(3.0));
    assert_eq!(
        net.object(shed.object).map(|o| o.name.as_str()),
        Some("Shed")
    );

    // A reference that gives neither is for both directions, with no valid
    // length.
    let post = referenced[1];
    assert_eq!(post.od_id, "5");
    assert_eq!(
        (post.orientation, post.valid_length),
        (Orientation::Both, None)
    );
}

#[test]
fn a_referenced_repeat_moves_with_the_reference_and_stops_at_the_road_end() {
    let poles: Vec<_> = on("1")
        .into_iter()
        .filter(|o| o.kind == ObjectType::Pole)
        .collect();
    // The row covers s = 5..85 in steps of 10 at t = -4..-6. The reference
    // moves it by (0, -1), so it runs at t = -5..-7, and road 1 ends at 60 m.
    assert_eq!(poles.len(), 6);
    for (k, pole) in poles.iter().enumerate() {
        let f = k as f64 / 8.0;
        let Shape::Solid { position, .. } = pole.shape else {
            panic!("a pole is not a solid");
        };
        let s = 5.0 + 10.0 * k as f64;
        assert_near(
            position,
            on_straight(s, -5.0 - 2.0 * f),
            &format!("pole {k}"),
        );
    }
}

#[test]
fn a_referenced_outline_moves_with_the_reference() {
    let referenced = on("1");

    // The house is outlined in its own frame, so it follows the frame to the
    // reference's station. The reference gives no zOffset, so it stands on
    // the road.
    let house = referenced
        .iter()
        .find(|o| o.name == "House")
        .expect("house");
    let (corners, closed) = outline(house);
    assert!(closed);
    let (sin, cos) = (0.2_f32.sin(), 0.2_f32.cos());
    let origin = on_straight(30.0, 8.0);
    for (corner, (u, v)) in corners
        .iter()
        .zip([(0.0, 0.0), (6.0, 0.0), (6.0, 4.0), (0.0, 4.0)])
    {
        let base = Point::new(
            origin.x + u * cos - v * sin,
            origin.y + u * sin + v * cos,
            origin.z,
        );
        assert_corner(corner, base, 5.0, &format!("house ({u}, {v})"));
    }

    // The fence is outlined in road coordinates from its <object> at
    // (50, -12). The reference at (20, 12) moves every corner by (-30, 24).
    let fence = referenced
        .iter()
        .find(|o| o.name == "Fence")
        .expect("fence");
    let (corners, closed) = outline(fence);
    assert!(!closed);
    assert_eq!(corners.len(), 3);
    for (corner, (s, t)) in corners
        .iter()
        .zip([(20.0, 12.0), (30.0, 12.0), (30.0, 10.0)])
    {
        assert_corner(corner, on_straight(s, t), 1.5, &format!("fence ({s}, {t})"));
    }
}

/// The `(road, <lane id>)` of each lane `object` applies to.
fn lanes_of(object: &Object) -> Vec<(String, i32)> {
    let (_, prov) = load_file_with_provenance(OBJECTS).expect("objects.xodr loads");
    object
        .lanes
        .iter()
        .map(|id| {
            let p = prov.lanes.iter().find(|p| p.lane == *id).expect("lane");
            (p.road_id.clone(), p.od_id)
        })
        .collect()
}

#[test]
fn validity_narrows_the_lanes_an_object_applies_to() {
    let road = |ids: &[i32], road: &str| {
        ids.iter()
            .map(|&id| (road.to_string(), id))
            .collect::<Vec<_>>()
    };
    let objects = objects();
    // The shed is valid for lane -1 only.
    assert_eq!(lanes_of(&objects[0]), road(&[-1], "0"));
    // The tree gives no <validity>, so it applies to both lanes.
    assert_eq!(lanes_of(&objects[1]), road(&[1, -1], "0"));

    // The shed's reference gives its own validity, on road 1's lanes.
    let referenced = on("1");
    assert_eq!(lanes_of(&referenced[0]), road(&[1], "1"));
    // A reference that gives none applies to every lane on its road, not
    // the <object>'s, which are on road 0.
    assert_eq!(lanes_of(&referenced[1]), road(&[1, -1], "1"));
}

#[test]
fn a_reference_to_no_object_is_skipped() {
    let (_, prov) = load_file_with_provenance(OBJECTS).expect("objects.xodr loads");
    assert!(prov.objects.iter().all(|p| p.od_id != "99"));
    // The shed, six posts, the house and the fence.
    assert_eq!(on("1").len(), 1 + 6 + 1 + 1);
}

#[test]
fn a_real_file_expands_its_rows_of_posts_and_sweeps_its_railings() {
    // e6mini lines a 1464 m road with a pole every 4 m and a guide post every
    // 50 m on each side, and a continuous railing on each side.
    let net = load_file(E6MINI).expect("e6mini loads");
    const ROAD_LENGTH: f64 = 1_464.434_350_705_6;
    let per_side_poles = (ROAD_LENGTH / 4.0).floor() as usize + 1;
    let per_side_guides = (ROAD_LENGTH / 50.0).floor() as usize + 1;
    let sweeps = net
        .objects()
        .iter()
        .filter(|o| matches!(o.shape, Shape::Sweep { .. }))
        .count();
    assert_eq!(sweeps, 2);
    assert_eq!(
        net.objects().len(),
        2 * (per_side_poles + per_side_guides + 1)
    );
    // The posts give a height and no footprint.
    assert!(net.objects().iter().all(|o| match &o.shape {
        Shape::Solid { extent, .. } => matches!(extent, Some(Extent::Box { length, width, height })
            if *length == 0.0 && *width == 0.0 && *height > 0.0),
        _ => true,
    }));
}

#[cfg(feature = "serde")]
#[test]
fn objects_survive_a_round_trip() {
    let net = load_file(OBJECTS).expect("objects.xodr loads");
    let json = serde_json::to_string(&net).expect("serialize");
    let back: libopendrive::RoadNetwork = serde_json::from_str(&json).expect("deserialize");
    assert_eq!(back.objects(), net.objects());
    assert_eq!(back, net);
}

/// Checks `piece` paints `width` across the line from `from` to `to`, and
/// goes anticlockwise seen from above.
fn assert_piece(piece: &[Point; 4], from: Point, to: Point, width: f32, what: &str) {
    let [a, b, c, d] = *piece;
    assert_near(a.lerp(d, 0.5), from, &format!("{what} start"));
    assert_near(b.lerp(c, 0.5), to, &format!("{what} end"));
    assert!((a.distance_to(d) - width).abs() < 1e-4, "{what} width");
    assert!((b.distance_to(c) - width).abs() < 1e-4, "{what} width");
    let area = (b - a).cross(d - a).z;
    assert!(area > 0.0, "{what} winds clockwise");
}

fn crosswalk_markings() -> Vec<Marking> {
    let crosswalk = objects()
        .into_iter()
        .find(|o| o.kind == ObjectType::Crosswalk)
        .expect("the crosswalk");
    crosswalk.markings
}

#[test]
fn a_dashed_marking_paints_along_the_edge_it_references() {
    let stripes = &crosswalk_markings()[0];
    assert_eq!(
        (stripes.side.as_str(), stripes.color.as_str()),
        ("left", "white")
    );
    assert_eq!(
        (stripes.width, stripes.line_length, stripes.space_length),
        (0.4, 0.5, 0.5)
    );
    // The edge from corner 0 at (13, -3) to corner 1 at (13, 3) is 6 m. Less
    // 0.25 m at either end, 0.5 m dashes 0.5 m apart make six.
    assert_eq!(stripes.pieces.len(), 6);
    let at = |x: f64| raised(13.0, -3.0 + x, 0.01);
    for (k, piece) in stripes.pieces.iter().enumerate() {
        let start = 0.25 + k as f64;
        assert_piece(piece, at(start), at(start + 0.5), 0.4, &format!("dash {k}"));
    }
}

#[test]
fn a_solid_marking_turns_the_corners_it_references() {
    let edge = &crosswalk_markings()[1];
    assert_eq!(
        (edge.side.as_str(), edge.color.as_str()),
        ("right", "yellow")
    );
    // Corners 1, 2 and 3: one piece along each of the two edges, raised the
    // default 5 mm.
    let corner = |s, t| raised(s, t, 0.005);
    assert_eq!(edge.pieces.len(), 2);
    assert_piece(
        &edge.pieces[0],
        corner(13.0, 3.0),
        corner(17.0, 3.0),
        0.2,
        "first edge",
    );
    assert_piece(
        &edge.pieces[1],
        corner(17.0, 3.0),
        corner(17.0, -3.0),
        0.2,
        "second edge",
    );
}

#[test]
fn only_the_crosswalk_and_the_parking_bays_carry_markings() {
    assert!(objects()
        .iter()
        .filter(|o| !matches!(o.kind, ObjectType::Crosswalk | ObjectType::ParkingSpace))
        .all(|o| o.markings.is_empty()));
}

#[test]
#[allow(clippy::approx_constant)] // The bays' hdg, as the file gives it.
fn a_marking_with_no_corners_paints_a_side_of_the_box() {
    let bays: Vec<Object> = of_kind(ObjectType::ParkingSpace);
    // A 5.5 x 2.5 m bay at (s, -9), turned a right angle against the road.
    // The paint is 5 mm up, as the markings give no zOffset.
    let corner = |s: f64, (u, v): (f32, f32)| {
        placed(s, -9.0, 0.0, (1.5708, 0.0, 0.0), [u, v, 0.0]) + Vector::Z * 0.005
    };
    let (u, v) = (2.75, 1.25);

    // Each edge runs anticlockwise round the box: the left side from front
    // to rear, the right from rear to front.
    let [left, right] = &bays[0].markings[..] else {
        panic!("two markings: {:?}", bays[0].markings);
    };
    for (m, side, from, to) in [
        (left, "left", (u, v), (-u, v)),
        (right, "right", (-u, -v), (u, -v)),
    ] {
        assert_eq!((m.side.as_str(), m.color.as_str()), (side, "white"));
        assert_eq!(m.pieces.len(), 1, "{side} is one solid line");
        assert_piece(
            &m.pieces[0],
            corner(26.0, from),
            corner(26.0, to),
            0.1,
            side,
        );
    }

    // The rear, dashed every metre across the bay's 2.5 m width.
    let [rear] = &bays[1].markings[..] else {
        panic!("one marking: {:?}", bays[1].markings);
    };
    assert_eq!(
        (rear.side.as_str(), rear.color.as_str()),
        ("rear", "yellow")
    );
    assert_eq!(rear.pieces.len(), 3);
    for (k, piece) in rear.pieces.iter().enumerate() {
        let from = v - k as f32;
        assert_piece(
            piece,
            corner(32.0, (-u, from)),
            corner(32.0, (-u, from - 0.5)),
            0.1,
            &format!("dash {k}"),
        );
    }
}

#[test]
fn a_parking_space_says_who_may_park_there() {
    let bays: Vec<_> = objects()
        .into_iter()
        .filter(|o| o.kind == ObjectType::ParkingSpace)
        .map(|o| o.parking_space.expect("a parking space"))
        .collect();
    assert_eq!(
        bays,
        [
            ParkingSpace {
                access: "handicapped".into(),
                restrictions: "".into()
            },
            ParkingSpace {
                access: "all".into(),
                restrictions: "2 hours".into()
            },
        ]
    );
    assert!(objects()
        .iter()
        .filter(|o| o.kind != ObjectType::ParkingSpace)
        .all(|o| o.parking_space.is_none()));
}

#[test]
fn an_object_keeps_what_its_surface_is_made_of() {
    let objects = objects();
    let of = |kind| {
        objects
            .iter()
            .find(|o| o.kind == kind)
            .map(|o| o.materials.clone())
            .expect("object")
    };
    assert_eq!(
        of(ObjectType::TrafficIsland),
        [Material {
            surface: "concrete".into(),
            friction: Some(0.7),
            roughness: Some(0.02)
        }]
    );
    assert_eq!(
        of(ObjectType::Crosswalk),
        [Material {
            surface: "asphalt".into(),
            friction: Some(0.6),
            roughness: None
        }]
    );
    assert_eq!(of(ObjectType::Tree), []);
}

#[test]
fn an_object_keeps_its_user_data_as_text() {
    let island = objects()
        .into_iter()
        .find(|o| o.kind == ObjectType::TrafficIsland)
        .expect("the island");
    let pair = |code: &str, value: &str| UserData {
        code: code.into(),
        value: value.into(),
    };
    assert_eq!(
        island.user_data,
        [
            pair("builder", "county roads"),
            pair("inspected", "2026-04")
        ]
    );
    assert!(objects()[0].user_data.is_empty());
}

#[test]
fn a_border_runs_round_the_whole_outline_or_along_the_edges_it_references() {
    let island = objects()
        .into_iter()
        .find(|o| o.kind == ObjectType::TrafficIsland)
        .expect("the island");
    let corner = |s, t| raised(s, t, 0.0);
    let [curb, paint] = &island.borders[..] else {
        panic!("two borders: {:?}", island.borders);
    };

    // All four edges, the closing one too, level with the outline's base.
    assert_eq!((curb.kind.as_str(), curb.width), ("curb", 0.3));
    let round = [
        (64.0, -1.0),
        (70.0, -1.0),
        (70.0, 1.0),
        (64.0, 1.0),
        (64.0, -1.0),
    ];
    assert_eq!(curb.pieces.len(), 4);
    for (k, piece) in curb.pieces.iter().enumerate() {
        let ((s0, t0), (s1, t1)) = (round[k], round[k + 1]);
        assert_piece(
            piece,
            corner(s0, t0),
            corner(s1, t1),
            0.3,
            &format!("edge {k}"),
        );
    }

    // Corners 1 and 2 only: the s = 70 end.
    assert_eq!((paint.kind.as_str(), paint.width), ("paint", 0.5));
    assert_eq!(paint.pieces.len(), 1);
    assert_piece(
        &paint.pieces[0],
        corner(70.0, -1.0),
        corner(70.0, 1.0),
        0.5,
        "end",
    );
}

#[test]
fn an_object_leans_with_a_banked_road() {
    // Road 2 banks 0.15 rad about its reference line, so the kiosk at t = -5
    // is 5 cos 0.15 right of it and 5 sin 0.15 down. Its zOffset raises it
    // square to the bank, and it rolls with it.
    let kiosk = &on("2")[0];
    let Shape::Solid {
        position,
        heading,
        pitch,
        roll,
        ..
    } = kiosk.shape
    else {
        panic!("a solid: {:?}", kiosk.shape);
    };
    let (sin, cos) = 0.15_f32.sin_cos();
    let want = Point::new(20.0, -80.0 - 5.0 * cos - 0.2 * sin, -5.0 * sin + 0.2 * cos);
    assert_near(position, want, "kiosk");
    assert!(
        heading.abs() < 1e-6 && pitch.abs() < 1e-6,
        "{heading}, {pitch}"
    );
    assert!((roll - 0.15).abs() < 1e-6, "roll {roll}");
}

#[test]
fn a_repeat_moves_the_outlines_to_each_step() {
    // Road 2 banks 0.15 rad, so each planter's frame is the bank's: u along
    // +X, v up the bank, and its height square to it.
    let planters: Vec<Object> = on("2")
        .into_iter()
        .filter(|o| o.name == "Planter")
        .collect();
    assert_eq!(planters.len(), 4);
    let (sin, cos) = 0.15_f32.sin_cos();
    for (planter, s) in planters.iter().zip([5.0, 15.0, 25.0, 35.0]) {
        let (corners, closed) = outline(planter);
        assert!(closed);
        for (corner, (u, v)) in corners
            .iter()
            .zip([(0.0, 0.0), (1.5, 0.0), (1.5, 1.0), (0.0, 1.0)])
        {
            let t = 5.0 + v;
            let base = Point::new(s + u, -80.0 + t * cos, t * sin);
            let what = format!("planter at s={s} ({u}, {v})");
            assert_near(corner.base, base, &format!("{what} base"));
            let top = base + Vector::new(0.0, -sin, cos) * 0.6;
            assert_near(corner.top, top, &format!("{what} top"));
        }
    }
}
