//! Objects placed along a road land where the road says they are.
//!
//! `objects.xodr` is generated by `scenariogeneration` (see `objects.py`), so
//! the file comes from a writer other than this crate. Its road is a 100 m arc
//! of curvature 0.005 from the origin heading +X, at elevation `1 + 0.02 s`,
//! which puts every expected placement in closed form.

use libopendrive::{load_file, Extent, Object, ObjectType, Point};

const OBJECTS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/objects.xodr");
const E6MINI: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/e6mini.xodr");

const CURVATURE: f64 = 0.005;

/// The road surface at `(s, t)`, and the reference line's heading there.
fn on_road(s: f64, t: f64) -> (Point, f64) {
    let hdg = CURVATURE * s;
    let x = hdg.sin() / CURVATURE - t * hdg.sin();
    let y = (1.0 - hdg.cos()) / CURVATURE + t * hdg.cos();
    let z = 1.0 + 0.02 * s;
    (Point::new(x as f32, y as f32, z as f32), hdg)
}

fn assert_at(object: &Object, s: f64, t: f64, z_offset: f32, hdg: f64) {
    let (mut expected, road_hdg) = on_road(s, t);
    expected.z += z_offset;
    let miss = (object.position - expected).length();
    assert!(
        miss < 1e-3,
        "{} at s={s} t={t}: got {:?}, expected {expected:?}",
        object.kind,
        object.position
    );
    let expected_heading = (road_hdg + hdg) as f32;
    assert!(
        (object.heading - expected_heading).abs() < 1e-5,
        "{} at s={s}: heading {} expected {expected_heading}",
        object.kind,
        object.heading
    );
}

fn objects() -> Vec<Object> {
    load_file(OBJECTS)
        .expect("objects.xodr loads")
        .objects()
        .to_vec()
}

#[test]
fn single_objects_sit_on_the_road_surface_at_their_station() {
    let objects = objects();

    let shed = &objects[0];
    assert_eq!(shed.kind, ObjectType::Building);
    assert_eq!(shed.name, "Shed");
    assert_at(shed, 40.0, -6.0, 0.5, 0.3);
    assert_eq!(
        shed.extent,
        Some(Extent::Box {
            length: 8.0,
            width: 4.0,
            height: 3.0
        })
    );

    let tree = &objects[1];
    assert_eq!(tree.kind, ObjectType::Tree);
    assert_eq!(tree.name, "");
    assert_at(tree, 60.0, 5.0, 0.0, 0.0);
    assert_eq!((tree.pitch, tree.roll), (0.1, -0.2));
    assert_eq!(
        tree.extent,
        Some(Extent::Cylinder {
            radius: 1.5,
            height: 7.0
        })
    );

    let marker = &objects[2];
    assert_eq!(marker.kind, ObjectType::None);
    assert_at(marker, 10.0, 0.0, 0.0, 0.0);
    assert_eq!(marker.extent, None);

    // A vendor's own type is still an object, with the position the file
    // gives it. Only its category is lost.
    let post = &objects[3];
    assert_eq!(post.kind, ObjectType::Unknown);
    assert_at(post, 20.0, 4.0, 0.0, 0.0);
}

#[test]
fn a_repeat_becomes_one_object_per_step_with_its_values_interpolated() {
    let poles: Vec<_> = objects()
        .into_iter()
        .filter(|o| o.kind == ObjectType::Pole)
        .collect();
    // s = 5, 15, ..., 85: nine steps of 10 m over 80 m, both ends included.
    assert_eq!(poles.len(), 9);
    for (k, pole) in poles.iter().enumerate() {
        let f = k as f64 / 8.0;
        let s = 5.0 + 10.0 * k as f64;
        assert_at(pole, s, -4.0 - 2.0 * f, 0.0, 0.0);
        assert_eq!(
            pole.extent,
            Some(Extent::Cylinder {
                radius: 0.1,
                height: (1.0 + f) as f32
            })
        );
    }
}

#[test]
fn a_continuous_repeat_bakes_no_object() {
    let objects = objects();
    assert!(objects.iter().all(|o| o.kind != ObjectType::Railing));
    assert_eq!(objects.len(), 4 + 9);
}

#[test]
fn a_real_file_expands_its_rows_of_posts() {
    // e6mini lines a 1464 m road with a pole every 4 m and a guide post every
    // 50 m on each side, and with two continuous railings, which are dropped.
    let net = load_file(E6MINI).expect("e6mini loads");
    const ROAD_LENGTH: f64 = 1_464.434_350_705_6;
    let per_side_poles = (ROAD_LENGTH / 4.0).floor() as usize + 1;
    let per_side_guides = (ROAD_LENGTH / 50.0).floor() as usize + 1;
    assert_eq!(net.objects().len(), 2 * (per_side_poles + per_side_guides));
    assert!(net
        .objects()
        .iter()
        .all(|o| o.position.to_array().iter().all(|c| c.is_finite())));
}

#[cfg(feature = "serde")]
#[test]
fn objects_survive_a_round_trip() {
    let net = load_file(OBJECTS).expect("objects.xodr loads");
    let json = serde_json::to_string(&net).expect("serialize");
    let back: libopendrive::RoadNetwork = serde_json::from_str(&json).expect("deserialize");
    assert_eq!(back.objects(), net.objects());
    assert_eq!(back, net);
}
