//! `<railroad>` switches and `<station>`s.
//!
//! `tests/data/railways.xodr` is generated by `railways.py`.

use xodr::{
    load_file_with_provenance, load_str_with_provenance, Platform, PlatformSegment, RoadNetwork,
    Side, Station, Switch, SwitchPosition, TrackPoint,
};

const FIXTURE: &str = "tests/data/railways.xodr";

fn road(net: &RoadNetwork, od_id: &str) -> xodr::RoadId {
    net.road_by_od_id(od_id).unwrap().id()
}

#[test]
fn a_switch_names_the_point_on_each_track_and_its_partner() {
    let (net, _) = load_file_with_provenance(FIXTURE).unwrap();
    assert_eq!(
        net.switches(),
        [Switch {
            road: road(&net, "1"),
            od_id: "7".into(),
            name: "Points".into(),
            position: SwitchPosition::Straight,
            main: TrackPoint {
                road: road(&net, "1"),
                s: 30.0,
                forward: true,
            },
            side: TrackPoint {
                road: road(&net, "2"),
                s: 0.0,
                forward: true,
            },
            partner: Some("8".into()),
        }]
    );
}

#[test]
fn a_station_keeps_its_platforms_beside_their_track() {
    let (net, _) = load_file_with_provenance(FIXTURE).unwrap();
    assert_eq!(
        net.stations(),
        [Station {
            od_id: "20".into(),
            name: "Halt".into(),
            kind: "small".into(),
            platforms: vec![Platform {
                od_id: "20-1".into(),
                name: "Up".into(),
                segments: vec![PlatformSegment {
                    road: road(&net, "1"),
                    s_start: 50.0,
                    s_end: 80.0,
                    side: Side::Right,
                }],
            }],
        }]
    );
}

#[test]
fn a_switch_or_segment_it_cannot_place_is_dropped_with_a_warning() {
    let (_, prov) = load_file_with_provenance(FIXTURE).unwrap();
    let dropped: Vec<String> = prov.warnings.iter().map(|w| w.to_string()).collect();
    assert_eq!(
        dropped,
        [
            "road \"1\": switch \"9\" dropped",
            "road \"1\": platform segment \"20-1\" dropped",
        ]
    );
}

#[test]
fn a_platform_segment_ending_before_it_starts_is_dropped_with_a_warning() {
    let xml = std::fs::read_to_string(FIXTURE).unwrap().replace(
        r#"sStart="50" sEnd="80" side="right""#,
        r#"sStart="80" sEnd="50" side="right""#,
    );
    let (net, prov) = load_str_with_provenance(&xml).unwrap();
    assert!(net.stations()[0].platforms[0].segments.is_empty());
    let dropped = prov
        .warnings
        .iter()
        .filter(|w| w.to_string() == "road \"1\": platform segment \"20-1\" dropped")
        .count();
    assert_eq!(dropped, 2);
}
