//! Road `<neighbor>`: a road naming the road that runs beside it.
//!
//! `tests/data/road_neighbors.xodr` is generated by `road_neighbors.py`.

use libopendrive::{load_file_with_provenance, RoadNeighbor, RoadNetwork, Side, Warning};

const FIXTURE: &str = "tests/data/road_neighbors.xodr";

fn id(net: &RoadNetwork, od_id: &str) -> libopendrive::RoadId {
    net.road_by_od_id(od_id).unwrap().id()
}

#[test]
fn each_neighbor_names_its_road_the_road_beside_it_its_side_and_its_direction() {
    let (net, _) = load_file_with_provenance(FIXTURE).unwrap();
    let (one, two, three) = (id(&net, "1"), id(&net, "2"), id(&net, "3"));
    assert_eq!(
        net.road_neighbors(),
        [
            RoadNeighbor {
                road: one,
                neighbor: two,
                side: Side::Left,
                same_direction: true,
            },
            RoadNeighbor {
                road: one,
                neighbor: three,
                side: Side::Right,
                same_direction: false,
            },
            RoadNeighbor {
                road: two,
                neighbor: one,
                side: Side::Right,
                same_direction: true,
            },
        ]
    );
}

#[test]
fn a_neighbor_it_cannot_read_is_dropped_with_a_warning() {
    let (_, prov) = load_file_with_provenance(FIXTURE).unwrap();
    let dropped: Vec<_> = prov
        .warnings
        .iter()
        .filter(|w| matches!(w, Warning::NeighborDropped { .. }))
        .map(|w| w.to_string())
        .collect();
    assert_eq!(
        dropped,
        [
            "road \"2\": <neighbor> road \"9\", side \"left\", direction \"same\" dropped",
            "road \"3\": <neighbor> road \"1\", side \"up\", direction \"opposite\" dropped",
        ]
    );
}
