//! Signal `<semantics>`, `<staticBoard>` and `<vmsBoard>`: what a signal
//! means, and the boards it is.
//!
//! `tests/data/signal_semantics.xodr` is generated by
//! `signal_semantics.py`.

use xodr::{
    load_file, load_str, BoardSign, DisplayArea, MessageBoard, Point, RoadNetwork, RoadUser,
    Semantic, Signal, SignalBoard, Unit,
};

fn net() -> RoadNetwork {
    load_file("tests/data/signal_semantics.xodr").unwrap()
}

fn signal(net: &RoadNetwork, name_index: usize) -> &Signal {
    &net.signals()[name_index]
}

fn near(got: Point, want: [f32; 3]) {
    assert!(
        (got - Point::from_array(want)).length() < 1e-4,
        "{got:?} != {want:?}"
    );
}

#[test]
fn semantics_say_what_a_sign_means_and_skip_what_the_spec_does_not_name() {
    let net = net();
    assert_eq!(
        signal(&net, 0).semantics,
        [
            Semantic::Speed {
                kind: "maximum".into(),
                value: Some(50.0),
                unit: Some(Unit::KilometrePerHour),
            },
            Semantic::SupplementaryAllows(vec![
                RoadUser::Vehicle("bus".into()),
                RoadUser::Person("pedestrian".into()),
            ]),
        ]
    );
    assert_eq!(
        signal(&net, 3).semantics,
        [Semantic::Priority {
            kind: "stopLine".into()
        }]
    );
    assert!(signal(&net, 0).boards.is_empty());
}

#[test]
fn a_static_boards_signs_stand_on_it_where_v_and_z_put_them() {
    let net = net();
    let gantry = signal(&net, 1);
    // The board faces -X, so its left, +v, is -Y.
    near(gantry.position, [30.0, -5.0, 5.0]);
    let [SignalBoard::Static(signs)] = &gantry.boards[..] else {
        panic!("one static board");
    };
    assert_eq!(signs.len(), 2);
    let BoardSign {
        kind,
        value,
        semantics,
        position,
        width,
        ..
    } = &signs[0];
    assert_eq!(
        (kind.as_str(), *value, *width),
        ("274", Some(60.0), Some(0.8))
    );
    assert_eq!(semantics.len(), 1);
    near(*position, [30.0, -6.0, 5.5]);
    near(signs[1].position, [30.0, -4.0, 5.5]);
    assert_eq!(
        signs[1].semantics,
        [Semantic::Prohibited(vec![RoadUser::Vehicle(
            "truck".into()
        )])]
    );
}

#[test]
fn a_message_board_keeps_its_display_and_its_areas() {
    let net = net();
    let [SignalBoard::Message(MessageBoard {
        display,
        width,
        height,
        areas,
        ..
    })] = &signal(&net, 2).boards[..]
    else {
        panic!("one message board");
    };
    assert_eq!(
        (display.as_str(), *width, *height),
        ("LED", Some(4.0), Some(2.0))
    );
    let DisplayArea {
        index, position, ..
    } = &areas[1];
    assert_eq!(*index, Some(1));
    near(*position, [60.0, -6.0, 5.5]);
}

#[test]
fn a_display_area_index_with_spaces_round_it_is_read() {
    let xml = std::fs::read_to_string("tests/data/signal_semantics.xodr")
        .unwrap()
        .replace(r#"<displayArea index="1""#, r#"<displayArea index=" 1 ""#);
    let net = load_str(&xml).unwrap();
    let [SignalBoard::Message(MessageBoard { areas, .. })] = &signal(&net, 2).boards[..] else {
        panic!("one message board");
    };
    assert_eq!(areas[1].index, Some(1));
}
