//! Signals stand where the road says, face the traffic they address, and
//! apply to the lanes that traffic uses.
//!
//! `signals.xodr` is generated by `scenariogeneration` (see `signals.py`).
//! Its road 0 is a 120 m straight from the origin heading +X at elevation
//! `0.02 s`, with lanes 1, 2, -1 and -2, each 3 m wide. Road 1 is a 60 m
//! straight from `(0, -40)` heading +X, banked at 0.15 rad. Road 2 is a flat
//! 60 m straight from `(0, 40)` heading +X. That puts every expected
//! placement in closed form.

use std::f32::consts::PI;

use xodr::{
    load_file_with_provenance, Control, Dependency, JunctionControllerProvenance, Orientation,
    Point, Provenance, Reference, Referenced, RoadNetwork, Signal, SignalProvenance,
    SignalReferenceProvenance, Unit,
};

const SIGNALS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/signals.xodr");
const STRAIGHT_SIGNS: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/data/straight_500m_signs.xodr"
);

fn load(path: &str) -> (RoadNetwork, Provenance) {
    load_file_with_provenance(path).expect("the map loads")
}

/// The signal whose `<signal id>` is `od_id`, and its provenance.
fn find<'a>(
    net: &'a RoadNetwork,
    prov: &'a Provenance,
    od_id: &str,
) -> (&'a Signal, &'a SignalProvenance) {
    let p = prov
        .signals
        .iter()
        .find(|p| p.od_id == od_id)
        .unwrap_or_else(|| panic!("no signal {od_id}"));
    (net.signal(p.signal).expect("a baked signal"), p)
}

/// The `(road, <lane id>)` of each lane `signal` applies to.
fn lanes(prov: &Provenance, signal: &Signal) -> Vec<(String, i32)> {
    signal
        .lanes
        .iter()
        .map(|id| {
            let p = prov.lanes.iter().find(|p| p.lane == *id).expect("a lane");
            (p.road_id.clone(), p.od_id)
        })
        .collect()
}

fn on(road: &str, ids: &[i32]) -> Vec<(String, i32)> {
    ids.iter().map(|&id| (road.to_string(), id)).collect()
}

fn assert_near(got: Point, want: Point, what: &str) {
    assert!(
        (got - want).length() < 1e-3,
        "{what}: got {got:?}, expected {want:?}"
    );
}

fn assert_angle(got: f32, want: f32, what: &str) {
    assert!(
        (got - want).abs() < 1e-5,
        "{what}: got {got}, expected {want}"
    );
}

#[test]
fn a_signal_keeps_what_the_map_says_it_means() {
    let (net, prov) = load(SIGNALS);
    let (limit, p) = find(&net, &prov, "1");
    assert_eq!(limit.name, "SpeedLimit50");
    assert!(!limit.dynamic);
    assert_eq!(limit.country, "DE");
    assert_eq!(limit.country_revision, "2017");
    assert_eq!(limit.kind, "274");
    assert_eq!(limit.subtype, "55");
    assert_eq!(limit.value, Some(50.0));
    assert_eq!(limit.unit, Some(Unit::KilometrePerHour));
    assert_eq!(limit.text, "");
    assert!(!limit.invalidated && !limit.temporary);
    assert_eq!(
        (limit.width, limit.height, limit.length),
        (Some(0.6), Some(0.6), None)
    );
    assert_eq!(p.road_id, "0");
    assert_eq!(
        (p.s, p.t, p.orientation),
        (20.0, -7.0, Orientation::Positive)
    );

    let (town, _) = find(&net, &prov, "3");
    assert_eq!(town.text, "Gate Town");
    assert_eq!((town.value, town.unit), (None, None));

    let (light, _) = find(&net, &prov, "4");
    assert!(light.dynamic);
    assert_eq!(light.country, "OPENDRIVE");
    assert_eq!(light.length, Some(0.3));

    let (works, _) = find(&net, &prov, "6");
    assert!(works.invalidated && works.temporary);

    let (weight, _) = find(&net, &prov, "9");
    assert_eq!((weight.value, weight.unit), (Some(3.5), Some(Unit::Tonne)));
}

#[test]
fn a_board_stands_its_z_offset_above_the_road_and_faces_its_traffic() {
    let (net, prov) = load(SIGNALS);
    let (limit, _) = find(&net, &prov, "1");
    assert_near(limit.position, Point::new(20.0, -7.0, 0.4 + 2.0), "limit");
    assert_eq!(limit.applies_at[0], Point::new(20.0, -7.0, 0.4));
    assert_angle(limit.heading, PI, "a + sign faces back along the road");

    let (town, _) = find(&net, &prov, "3");
    assert_near(town.position, Point::new(40.0, 7.0, 0.8 + 1.5), "town sign");
    assert_angle(
        town.heading,
        0.3,
        "a - sign faces along the road, turned hOffset",
    );

    let (works, _) = find(&net, &prov, "6");
    assert_angle(works.heading, 0.0, "a none sign is turned from the road");
    assert_angle(works.pitch, 0.1, "pitch");
    assert_angle(works.roll, -0.05, "roll");
}

#[test]
fn a_heading_offset_of_many_turns_wraps() {
    let (net, prov) = load(SIGNALS);
    let (light, _) = find(&net, &prov, "4");
    assert_angle(light.heading, PI, "15 pi wraps to pi");
    for signal in net.signals() {
        assert!(
            signal.heading > -PI && signal.heading <= PI,
            "{} heads {}",
            signal.name,
            signal.heading
        );
    }
}

#[test]
fn a_board_on_a_banked_road_stays_upright() {
    let (net, prov) = load(SIGNALS);
    let (sign, _) = find(&net, &prov, "20");
    let bank = 0.15_f64;
    let ground = Point::new(
        30.0,
        (-40.0 - 5.0 * bank.cos()) as f32,
        (-5.0 * bank.sin()) as f32,
    );
    assert_near(sign.applies_at[0], ground, "ground");
    assert_near(
        sign.position,
        Point::new(ground.x, ground.y, ground.z + 2.0),
        "board",
    );
    assert_eq!((sign.pitch, sign.roll), (0.0, 0.0));
}

#[test]
fn a_position_road_stands_the_board_beside_another_road() {
    let (net, prov) = load(SIGNALS);
    let (sign, _) = find(&net, &prov, "7");
    assert_near(
        sign.position,
        Point::new(30.0, 36.0, 2.5),
        "board by road 2",
    );
    assert_angle(
        sign.heading,
        0.2 - PI,
        "faces back along road 2, turned 0.2",
    );
    assert_eq!(sign.applies_at, vec![Point::new(100.0, -7.0, 2.0)]);
    assert_eq!(lanes(&prov, sign), on("0", &[-1, -2]));
}

#[test]
fn a_position_inertial_stands_the_board_where_it_says() {
    let (net, prov) = load(SIGNALS);
    let (gantry, _) = find(&net, &prov, "8");
    assert_near(gantry.position, Point::new(110.0, -1.5, 7.2), "gantry");
    assert_angle(gantry.heading, PI, "hdg");
    assert_angle(gantry.pitch, 0.05, "pitch");
    assert_eq!(gantry.applies_at, vec![Point::new(110.0, -7.0, 2.2)]);
    assert_eq!(lanes(&prov, gantry), on("0", &[-1, -2]));
}

#[test]
fn a_signal_reference_applies_the_signal_on_another_road_too() {
    let (net, prov) = load(SIGNALS);
    let (limit, p) = find(&net, &prov, "1");
    let mut want = on("0", &[-1, -2]);
    want.extend(on("2", &[-1]));
    assert_eq!(
        lanes(&prov, limit),
        want,
        "the reference's validity narrows it"
    );
    assert_eq!(
        limit.applies_at,
        vec![Point::new(20.0, -7.0, 0.4), Point::new(10.0, 36.0, 0.0)]
    );
    assert_eq!(
        p.references,
        vec![SignalReferenceProvenance {
            road_id: "2".into(),
            s: 10.0,
            t: -4.0,
            orientation: Orientation::Positive,
        }]
    );

    let (light, _) = find(&net, &prov, "4");
    let mut want = on("0", &[-1]);
    want.extend(on("2", &[-1]));
    assert_eq!(
        lanes(&prov, light),
        want,
        "the reference's orientation picks the side"
    );
    assert_eq!(light.applies_at[1], Point::new(50.0, 36.0, 0.0));
}

#[test]
fn a_signal_reference_moves_no_board_and_one_to_no_signal_is_skipped() {
    let (net, prov) = load(SIGNALS);
    assert_eq!(net.signals().len(), 11);
    let (limit, _) = find(&net, &prov, "1");
    assert_near(limit.position, Point::new(20.0, -7.0, 2.4), "the board");
    let referenced: usize = prov.signals.iter().map(|p| p.references.len()).sum();
    assert_eq!(referenced, 2);
}

#[test]
fn a_controller_groups_its_signals_and_each_signal_names_it() {
    let (net, prov) = load(SIGNALS);
    assert_eq!(net.controllers().len(), 2);
    let approach = &net.controllers()[0];
    assert_eq!(approach.name, "Approach");
    assert_eq!(approach.sequence, Some(1));
    let (light, _) = find(&net, &prov, "4");
    let (side, _) = find(&net, &prov, "21");
    assert_eq!(
        approach.signals,
        vec![
            Control {
                signal: light.id,
                kind: "0".into()
            },
            Control {
                signal: side.id,
                kind: "0".into()
            },
        ]
    );
    assert_eq!(light.controllers, vec![approach.id]);
    assert_eq!(side.controllers, vec![approach.id]);
    assert_eq!(net.controller(approach.id), Some(approach));
    let (limit, _) = find(&net, &prov, "1");
    assert!(limit.controllers.is_empty());
}

#[test]
fn a_control_of_no_signal_is_skipped_and_its_controller_kept() {
    let (net, prov) = load(SIGNALS);
    let ghost = &net.controllers()[1];
    assert_eq!((ghost.name.as_str(), ghost.sequence), ("Ghost", None));
    assert!(ghost.signals.is_empty());
    assert_eq!(prov.controllers[1].od_id, "101");
}

#[test]
fn a_junction_lists_the_controllers_it_syncs() {
    let (_, prov) = load(SIGNALS);
    let junctions: Vec<_> = prov
        .controllers
        .iter()
        .map(|c| c.junctions.clone())
        .collect();
    assert_eq!(
        junctions,
        vec![
            vec![JunctionControllerProvenance {
                junction_id: "500".into(),
                kind: "sync".into(),
                sequence: Some(2),
            }],
            vec![JunctionControllerProvenance {
                junction_id: "500".into(),
                kind: String::new(),
                sequence: None,
            }],
        ]
    );
}

#[test]
fn a_signal_keeps_its_dependencies_and_references_as_ids() {
    let (net, prov) = load(SIGNALS);
    let (limit, _) = find(&net, &prov, "1");
    let (plate, _) = find(&net, &prov, "2");
    assert_eq!(
        limit.dependencies,
        vec![Dependency {
            signal: plate.id,
            kind: "lorries".into()
        }]
    );
    assert!(plate.dependencies.is_empty() && plate.references.is_empty());

    let (light, _) = find(&net, &prov, "4");
    let (stop, _) = find(&net, &prov, "5");
    let mast = prov
        .objects
        .iter()
        .find(|p| p.od_id == "30")
        .expect("the mast")
        .object;
    assert_eq!(
        light.references,
        vec![
            Reference {
                to: Referenced::Signal(stop.id),
                kind: "stopline".into()
            },
            Reference {
                to: Referenced::Object(mast),
                kind: "mast".into()
            },
        ]
    );
    assert_eq!(
        stop.dependencies,
        vec![Dependency {
            signal: light.id,
            kind: "light".into()
        }]
    );
}

#[test]
fn a_signal_applies_to_the_lanes_its_orientation_names_unless_its_validity_says() {
    let (net, prov) = load(SIGNALS);
    let applies = |id| lanes(&prov, find(&net, &prov, id).0);
    assert_eq!(applies("2"), on("0", &[-1, -2]), "+ is the right side");
    assert_eq!(applies("3"), on("0", &[1, 2]), "- is the left side");
    assert_eq!(applies("6"), on("0", &[1, 2, -1, -2]), "none is both");
    assert_eq!(applies("5"), on("0", &[-1]), "validity narrows it");
}

#[test]
fn a_validity_the_orientation_contradicts_still_names_the_lanes() {
    let (net, prov) = load(STRAIGHT_SIGNS);
    assert_eq!(net.signals().len(), 19);
    let (both_sides, p) = find(&net, &prov, "0");
    assert_eq!(p.orientation, Orientation::Positive);
    assert_eq!(lanes(&prov, both_sides), on("1", &[1, 2, 3, -1, -2, -3]));
}

#[test]
fn a_repeated_id_is_kept_on_each_signal() {
    let (_, prov) = load(STRAIGHT_SIGNS);
    let stations: Vec<f64> = prov
        .signals
        .iter()
        .filter(|p| p.od_id == "14")
        .map(|p| p.s)
        .collect();
    assert_eq!(stations, [120.0, 160.0]);
}

#[test]
fn a_country_is_kept_as_the_map_spells_it() {
    let (net, _) = load(STRAIGHT_SIGNS);
    let mut countries: Vec<&str> = net.signals().iter().map(|s| s.country.as_str()).collect();
    countries.sort();
    countries.dedup();
    assert_eq!(countries, ["", "cn", "de", "se"]);
}

#[cfg(feature = "serde")]
#[test]
fn signals_survive_a_round_trip() {
    let net = xodr::load_file(SIGNALS).expect("signals.xodr loads");
    let json = serde_json::to_string(&net).expect("serialize");
    let back: RoadNetwork = serde_json::from_str(&json).expect("deserialize");
    assert_eq!(back.signals(), net.signals());
    assert_eq!(back.controllers(), net.controllers());
    assert_eq!(back, net);
}

#[test]
fn a_number_too_large_for_an_f32_reads_as_missing_not_infinite() {
    let signal = |id: &str, t: f64, extra: &str, inner: &str| {
        format!(
            r#"<signal id="{id}" s="10" t="{t}" orientation="+" dynamic="no" {extra}>{inner}</signal>"#
        )
    };
    let xodr = format!(
        r#"<OpenDRIVE><header/><road id="1" length="20" junction="-1"><planView>
        <geometry s="0" x="0" y="0" hdg="0" length="20"><line/></geometry></planView>
        <lanes><laneSection s="0"><center><lane id="0" type="none"/></center><right>
        <lane id="-1" type="driving"><width sOffset="0" a="3.5" b="0" c="0" d="0"/></lane>
        </right></laneSection></lanes><signals>{}{}{}</signals></road></OpenDRIVE>"#,
        signal(
            "size",
            -4.0,
            r#"width="1e39" height="1e39" length="1e39" zOffset="1e39""#,
            ""
        ),
        signal(
            "inertial",
            -4.0,
            "",
            r#"<positionInertial x="1e39" y="0" z="0" hdg="0"/>"#
        ),
        signal(
            "board",
            -4.0,
            "",
            r#"<staticBoard><sign v="1e39" z="0" width="1e39" height="1"/></staticBoard>"#
        ),
    );
    let net = xodr::load_str(&xodr).unwrap();
    let finite = |p: xodr::Point| p.to_array().iter().all(|c| c.is_finite());
    for s in net.signals() {
        assert!(finite(s.position), "{:?}", s.position);
        for size in [s.width, s.height, s.length] {
            assert!(size.is_none_or(f32::is_finite), "{size:?}");
        }
        for board in &s.boards {
            if let xodr::SignalBoard::Static(signs) = board {
                for sign in signs {
                    assert!(finite(sign.position), "{:?}", sign.position);
                    assert_eq!(sign.width, None);
                }
            }
        }
    }
    let size = &net.signals()[0];
    assert_eq!((size.width, size.height, size.length), (None, None, None));
    assert!((size.position.z - 0.0).abs() < 1e-3, "zOffset reads as 0");
    let inertial = &net.signals()[1];
    assert!(
        (inertial.position.x - 10.0).abs() < 1e-3,
        "the board stays at its station"
    );
}

#[test]
fn a_heading_just_over_minus_pi_stays_in_range() {
    let xodr = r#"<OpenDRIVE><header/><road id="1" length="20" junction="-1"><planView>
        <geometry s="0" x="0" y="0" hdg="0" length="20"><line/></geometry></planView>
        <lanes><laneSection s="0"><center><lane id="0" type="none"/></center><right>
        <lane id="-1" type="driving"><width sOffset="0" a="3.5" b="0" c="0" d="0"/></lane>
        </right></laneSection></lanes><signals>
        <signal id="s" s="10" t="-4" orientation="-" hOffset="-3.14159264"/>
        </signals></road></OpenDRIVE>"#;
    let heading = xodr::load_str(xodr).unwrap().signals()[0].heading;
    assert!(
        heading > -std::f32::consts::PI && heading <= std::f32::consts::PI,
        "{heading}"
    );
}
