//! Road types and speed limits: a road's `<type>`s with their `<speed>`,
//! and a lane's own `<speed>`s.
//!
//! `tests/data/speed_limits.xodr` is generated by `speed_limits.py`. Every
//! road there is a straight along +X, so a lane's distance along its
//! centerline is its road's `s` less the start of its lane section.

use libopendrive::{
    load_file_with_provenance, Along, LaneId, Provenance, RoadNetwork, RoadType, SpeedLimit,
    Warning,
};

const FIXTURE: &str = "tests/data/speed_limits.xodr";

fn fixture() -> (RoadNetwork, Provenance) {
    load_file_with_provenance(FIXTURE).expect("the fixture loads")
}

/// The baked lane `od_id` of lane section `section` on road `road`.
fn lane(prov: &Provenance, road: &str, section: usize, od_id: i32) -> LaneId {
    prov.lanes
        .iter()
        .find(|p| p.road_id == road && p.section == section && p.od_id == od_id)
        .unwrap_or_else(|| panic!("road {road} section {section} lane {od_id}"))
        .lane
}

/// Each stretch of `list` on `lane`, as `(from, to, value)`, rounded to the
/// millimetre.
fn on<T: Copy>(list: &[Along<T>], lane: LaneId) -> Vec<(f32, f32, T)> {
    let mm = |v: f32| (v * 1000.0).round() / 1000.0;
    list.iter()
        .filter(|a| a.lane == lane)
        .map(|a| (mm(a.from), mm(a.to), a.value))
        .collect()
}

const KMH: f32 = 1.0 / 3.6;
const MPH: f32 = 0.44704;

fn close(a: SpeedLimit, b: SpeedLimit) -> bool {
    match (a, b) {
        (SpeedLimit::Max(a), SpeedLimit::Max(b)) => (a - b).abs() < 1e-4,
        _ => a == b,
    }
}

fn assert_limits(got: Vec<(f32, f32, SpeedLimit)>, want: &[(f32, f32, SpeedLimit)]) {
    assert_eq!(got.len(), want.len(), "{got:?}");
    for (g, w) in got.iter().zip(want) {
        assert!(
            g.0 == w.0 && g.1 == w.1 && close(g.2, w.2),
            "{got:?} != {want:?}"
        );
    }
}

#[test]
fn a_lane_takes_the_speed_of_its_road_type() {
    let (net, prov) = fixture();
    assert_limits(
        on(net.speed_limits(), lane(&prov, "0", 0, -1)),
        &[
            (0.0, 30.0, SpeedLimit::Max(50.0 * KMH)),
            (30.0, 60.0, SpeedLimit::Unlimited),
            (60.0, 100.0, SpeedLimit::Max(60.0 * MPH)),
        ],
    );
}

#[test]
fn a_lane_speed_overrides_the_road_to_the_end_of_its_section() {
    let (net, prov) = fixture();
    assert_limits(
        on(net.speed_limits(), lane(&prov, "0", 0, -2)),
        &[
            (0.0, 10.0, SpeedLimit::Max(50.0 * KMH)),
            (10.0, 40.0, SpeedLimit::Max(20.0)),
            (40.0, 100.0, SpeedLimit::Max(30.0 * KMH)),
        ],
    );
}

#[test]
fn a_road_type_holds_to_the_next() {
    let (net, prov) = fixture();
    assert_eq!(
        on(net.road_types(), lane(&prov, "0", 0, 1)),
        vec![
            (0.0, 30.0, RoadType::Town),
            (30.0, 60.0, RoadType::Motorway),
            (60.0, 100.0, RoadType::Rural),
        ]
    );
}

#[test]
fn a_lane_speed_ends_with_its_lane_section() {
    let (net, prov) = fixture();
    assert_limits(
        on(net.speed_limits(), lane(&prov, "1", 0, -1)),
        &[(0.0, 20.0, SpeedLimit::Max(10.0))],
    );
    assert!(on(net.speed_limits(), lane(&prov, "1", 1, -1)).is_empty());
}

#[test]
fn nothing_holds_before_the_first_road_type_or_under_an_undefined_speed() {
    let (net, prov) = fixture();
    let first = lane(&prov, "1", 0, -1);
    assert_eq!(
        on(net.road_types(), first),
        vec![(5.0, 20.0, RoadType::Town)]
    );
    assert_eq!(net.road_type_at(first, 2.0), None);
    assert_eq!(net.road_type_at(first, 7.0), Some(RoadType::Town));
    assert_eq!(net.speed_limit_at(lane(&prov, "1", 1, -1), 5.0), None);
}

#[test]
fn speed_limit_at_reads_the_stretch_under_a_point() {
    let (net, prov) = fixture();
    let id = lane(&prov, "0", 0, -2);
    assert_eq!(net.speed_limit_at(id, 25.0), Some(SpeedLimit::Max(20.0)));
    let at_40 = net.speed_limit_at(id, 40.0).expect("a limit");
    assert!(close(at_40, SpeedLimit::Max(30.0 * KMH)), "{at_40:?}");
    assert_eq!(net.speed_limit_at(id, 100.5), None);
}

#[test]
fn an_unknown_road_type_is_unknown() {
    let (net, prov) = fixture();
    assert_eq!(
        net.road_type_at(lane(&prov, "2", 0, -1), 10.0),
        Some(RoadType::Unknown)
    );
}

#[test]
fn a_speed_the_crate_cannot_read_is_dropped_with_a_warning() {
    let (net, prov) = fixture();
    assert!(on(net.speed_limits(), lane(&prov, "2", 0, -1)).is_empty());
    assert_eq!(
        prov.warnings,
        vec![
            Warning::SpeedLimitDropped {
                road_id: "2".into(),
                s: 0.0,
                lane: None,
                max: "80".into(),
                unit: "kmh".into(),
            },
            Warning::SpeedLimitDropped {
                road_id: "2".into(),
                s: 0.0,
                lane: Some(-1),
                max: "fast".into(),
                unit: String::new(),
            },
        ]
    );
}

#[cfg(feature = "serde")]
#[test]
fn speed_limits_and_road_types_survive_a_serde_round_trip() {
    let (net, _) = fixture();
    let json = serde_json::to_string(&net).expect("serializes");
    let back: RoadNetwork = serde_json::from_str(&json).expect("deserializes");
    assert_eq!(back, net);
    assert!(!back.speed_limits().is_empty() && !back.road_types().is_empty());
}
