//! Traffic rules: `<road rule>` choosing which side drives along `+s`.
//!
//! `tests/data/traffic_rule.xodr` is generated by `traffic_rule.py`. Roads 0
//! and 1 are right-hand traffic, and roads 2 and 3 the same pair with
//! `rule="LHT"`. Road 4 has `rule="lht"`.

use xodr::{load_file_with_provenance, Direction, Lane, Provenance, RoadNetwork, Warning};

const FIXTURE: &str = "tests/data/traffic_rule.xodr";

fn fixture() -> (RoadNetwork, Provenance) {
    load_file_with_provenance(FIXTURE).expect("the fixture loads")
}

/// The baked lane `od_id` on road `road`.
fn lane<'a>(net: &'a RoadNetwork, prov: &Provenance, road: &str, od_id: i32) -> &'a Lane {
    let p = prov
        .lanes
        .iter()
        .find(|p| p.road_id == road && p.od_id == od_id)
        .unwrap_or_else(|| panic!("road {road} lane {od_id}"));
    net.lane(p.lane).expect("a baked lane")
}

#[test]
fn right_hand_traffic_drives_the_right_lanes_along_s() {
    let (net, prov) = fixture();
    assert_eq!(lane(&net, &prov, "0", -1).direction, Direction::Forward);
    assert_eq!(lane(&net, &prov, "0", 1).direction, Direction::Backward);
}

#[test]
fn left_hand_traffic_drives_the_left_lanes_along_s() {
    let (net, prov) = fixture();
    assert_eq!(lane(&net, &prov, "2", 1).direction, Direction::Forward);
    assert_eq!(lane(&net, &prov, "2", -1).direction, Direction::Backward);
}

#[test]
fn left_hand_traffic_links_the_left_lanes_onto_the_successor() {
    let (net, prov) = fixture();
    let (left_2, left_3) = (lane(&net, &prov, "2", 1), lane(&net, &prov, "3", 1));
    assert_eq!(left_2.successors, vec![left_3.id]);
    assert_eq!(left_3.predecessors, vec![left_2.id]);
    let (right_2, right_3) = (lane(&net, &prov, "2", -1), lane(&net, &prov, "3", -1));
    assert_eq!(right_3.successors, vec![right_2.id]);
    assert_eq!(right_2.predecessors, vec![right_3.id]);
    assert!(right_2.successors.is_empty(), "it leaves the map at s = 0");
}

#[test]
fn right_hand_traffic_links_the_right_lanes_onto_the_successor() {
    let (net, prov) = fixture();
    let (right_0, right_1) = (lane(&net, &prov, "0", -1), lane(&net, &prov, "1", -1));
    assert_eq!(right_0.successors, vec![right_1.id]);
    let (left_0, left_1) = (lane(&net, &prov, "0", 1), lane(&net, &prov, "1", 1));
    assert_eq!(left_1.successors, vec![left_0.id]);
}

#[test]
fn a_signal_facing_plus_s_applies_to_the_lanes_driving_along_s() {
    let (net, prov) = fixture();
    let on = |road: &str| {
        let p = prov
            .signals
            .iter()
            .find(|p| p.road_id == road)
            .expect("a signal");
        net.signals()[p.signal.0].lanes.clone()
    };
    assert_eq!(on("0"), vec![lane(&net, &prov, "0", -1).id]);
    assert_eq!(on("2"), vec![lane(&net, &prov, "2", 1).id]);
}

#[test]
fn a_rule_the_spec_does_not_allow_reads_as_right_hand_traffic() {
    let (net, prov) = fixture();
    assert_eq!(lane(&net, &prov, "4", -1).direction, Direction::Forward);
    assert_eq!(
        prov.warnings,
        vec![Warning::UnknownTrafficRule {
            road_id: "4".into(),
            rule: "lht".into(),
        }]
    );
}
