//! `<junction type="virtual">`: side roads meeting a main road part way
//! along it.
//!
//! `tests/data/virtual_junction.xodr` is generated by `virtual_junction.py`.

use xodr::{
    load_file_with_provenance, load_str_with_provenance, LaneId, LinkPoint, MainRoad, Orientation,
    RoadEnd, RoadNetwork, VirtualJunction, VirtualLink, Warning,
};

const FIXTURE: &str = "tests/data/virtual_junction.xodr";

fn lane(net: &RoadNetwork, road: &str, od_id: i32) -> LaneId {
    let road = net.road_by_od_id(road).unwrap().id();
    net.lanes()
        .iter()
        .map(|l| l.id)
        .find(|&id| {
            net.road_lane(id)
                .is_some_and(|at| at.road == road && at.od_id == od_id)
        })
        .unwrap()
}

#[test]
fn a_link_part_way_along_a_road_does_not_join_its_start() {
    let (net, _) = load_file_with_provenance(FIXTURE).unwrap();
    let exit = net.lane(lane(&net, "4", -1)).unwrap();
    assert!(exit.successors.is_empty());
    assert_eq!(exit.predecessors, [lane(&net, "99", 1)]);
    let entry = net.lane(lane(&net, "2", -1)).unwrap();
    assert!(entry.predecessors.is_empty());
    assert_eq!(entry.successors, [lane(&net, "99", -1)]);
    for od_id in [1, -1, -2] {
        let main = net.lane(lane(&net, "1", od_id)).unwrap();
        assert!(main.successors.is_empty() && main.predecessors.is_empty());
    }
}

#[test]
fn a_main_road_naming_its_virtual_junction_part_way_along_is_not_joined_to_its_roads() {
    let xml = std::fs::read_to_string(FIXTURE).unwrap().replacen(
        "<link></link>",
        r#"<link><successor elementType="junction" elementId="555" elementS="50" elementDir="+"/></link>"#,
        1,
    );
    let (net, prov) = load_str_with_provenance(&xml).unwrap();
    for od_id in [1, -1, -2] {
        let main = net.lane(lane(&net, "1", od_id)).unwrap();
        assert!(main.successors.is_empty() && main.predecessors.is_empty());
    }
    assert!(
        !prov
            .warnings
            .iter()
            .any(|w| matches!(w, Warning::LinkGap { .. })),
        "{:?}",
        prov.warnings
    );
}

#[test]
fn a_virtual_junction_keeps_where_its_roads_meet_the_main_road() {
    let (net, _) = load_file_with_provenance(FIXTURE).unwrap();
    let road = |id: &str| net.road_by_od_id(id).unwrap().id();
    let main = road("1");
    assert_eq!(
        net.virtual_junctions(),
        [VirtualJunction {
            od_id: "555".into(),
            name: "driveway".into(),
            main: Some(MainRoad {
                road: main,
                s_start: 45.0,
                s_end: 75.0,
            }),
            orientation: Orientation::Positive,
            links: vec![
                VirtualLink {
                    from: LinkPoint::Along {
                        road: main,
                        s: 50.0,
                        forward: true,
                    },
                    to: LinkPoint::End {
                        road: road("2"),
                        end: RoadEnd::Start,
                    },
                    lanes: vec![(lane(&net, "1", -2), lane(&net, "2", -1))],
                },
                VirtualLink {
                    from: LinkPoint::End {
                        road: road("4"),
                        end: RoadEnd::End,
                    },
                    to: LinkPoint::Along {
                        road: main,
                        s: 50.0,
                        forward: true,
                    },
                    lanes: vec![(lane(&net, "4", -1), lane(&net, "1", -2))],
                },
                VirtualLink {
                    from: LinkPoint::Along {
                        road: main,
                        s: 90.0,
                        forward: false,
                    },
                    to: LinkPoint::End {
                        road: road("99"),
                        end: RoadEnd::End,
                    },
                    lanes: vec![(lane(&net, "1", 1), lane(&net, "99", 1))],
                },
            ],
        }]
    );
}

#[test]
fn only_a_link_naming_a_road_the_file_lacks_is_dropped() {
    let (_, prov) = load_file_with_provenance(FIXTURE).unwrap();
    assert_eq!(
        prov.warnings,
        [Warning::VirtualLinkDropped {
            junction_id: "555".into(),
            road_id: String::new(),
            connection_id: "3".into(),
        }]
    );
}

#[test]
fn a_virtual_junction_without_its_main_road_keeps_its_links_with_a_warning() {
    let xml = std::fs::read_to_string(FIXTURE)
        .unwrap()
        .replace(r#"mainRoad="1" sStart="45" sEnd="75" "#, "");
    let (net, prov) = load_str_with_provenance(&xml).unwrap();
    let [junction] = net.virtual_junctions() else {
        panic!("one virtual junction");
    };
    assert_eq!(junction.main, None);
    assert_eq!(junction.links.len(), 3);
    assert!(prov
        .warnings
        .contains(&Warning::VirtualJunctionWithoutMainRoad {
            junction_id: "555".into()
        }));
}

#[test]
fn a_virtual_junction_off_its_main_road_has_none() {
    let xml = std::fs::read_to_string(FIXTURE)
        .unwrap()
        .replace(r#"sEnd="75""#, r#"sEnd="175""#);
    let (net, prov) = load_str_with_provenance(&xml).unwrap();
    assert_eq!(net.virtual_junctions()[0].main, None);
    assert!(prov
        .warnings
        .contains(&Warning::VirtualJunctionWithoutMainRoad {
            junction_id: "555".into()
        }));
}

#[test]
fn a_lane_pair_naming_a_missing_lane_is_left_out_with_a_warning() {
    let xodr = std::fs::read_to_string(FIXTURE).unwrap().replace(
        r#"<laneLink from="1" to="1"/></connection>"#,
        r#"<laneLink from="1" to="1"/><laneLink from="9" to="1"/></connection>"#,
    );
    let (net, prov) = xodr::load_str_with_provenance(&xodr).unwrap();
    assert!(prov.warnings.contains(&Warning::VirtualLaneDropped {
        junction_id: "555".into(),
        road_id: String::new(),
        connection_id: "2".into(),
        from: 9,
        to: 1,
    }));
    let link = net.virtual_junctions()[0]
        .links
        .iter()
        .find(|l| matches!(l.from, xodr::LinkPoint::Along { .. }) && l.lanes.len() == 1);
    assert!(link.is_some(), "the link keeps its good pair");
}
