//! `<junction type="virtual">`: side roads meeting a main road part way
//! along it.
//!
//! `tests/data/virtual_junction.xodr` is generated by `virtual_junction.py`.

use libopendrive::{load_file_with_provenance, LaneId, RoadNetwork};

const FIXTURE: &str = "tests/data/virtual_junction.xodr";

fn lane(net: &RoadNetwork, road: &str, od_id: i32) -> LaneId {
    let road = net.road_by_od_id(road).unwrap().id();
    net.lanes()
        .iter()
        .map(|l| l.id)
        .find(|&id| {
            net.road_lane(id)
                .is_some_and(|at| at.road == road && at.od_id == od_id)
        })
        .unwrap()
}

#[test]
fn a_link_part_way_along_a_road_does_not_join_its_start() {
    let (net, _) = load_file_with_provenance(FIXTURE).unwrap();
    let exit = net.lane(lane(&net, "4", -1)).unwrap();
    assert!(exit.successors.is_empty());
    assert_eq!(exit.predecessors, [lane(&net, "99", 1)]);
    let entry = net.lane(lane(&net, "2", -1)).unwrap();
    assert!(entry.predecessors.is_empty());
    assert_eq!(entry.successors, [lane(&net, "99", -1)]);
    for od_id in [1, -1, -2] {
        let main = net.lane(lane(&net, "1", od_id)).unwrap();
        assert!(main.successors.is_empty() && main.predecessors.is_empty());
    }
}

#[test]
fn a_virtual_junction_loads_without_warnings() {
    let (_, prov) = load_file_with_provenance(FIXTURE).unwrap();
    assert!(prov.warnings.is_empty(), "{:?}", prov.warnings);
}
