//! `<junction type="virtual">`: side roads meeting a main road part way
//! along it.
//!
//! `tests/data/virtual_junction.xodr` is generated by `virtual_junction.py`.

use libopendrive::{
    load_file_with_provenance, load_str_with_provenance, LaneId, LinkPoint, Orientation, RoadEnd,
    RoadNetwork, VirtualJunction, VirtualLink, Warning,
};

const FIXTURE: &str = "tests/data/virtual_junction.xodr";

fn lane(net: &RoadNetwork, road: &str, od_id: i32) -> LaneId {
    let road = net.road_by_od_id(road).unwrap().id();
    net.lanes()
        .iter()
        .map(|l| l.id)
        .find(|&id| {
            net.road_lane(id)
                .is_some_and(|at| at.road == road && at.od_id == od_id)
        })
        .unwrap()
}

#[test]
fn a_link_part_way_along_a_road_does_not_join_its_start() {
    let (net, _) = load_file_with_provenance(FIXTURE).unwrap();
    let exit = net.lane(lane(&net, "4", -1)).unwrap();
    assert!(exit.successors.is_empty());
    assert_eq!(exit.predecessors, [lane(&net, "99", 1)]);
    let entry = net.lane(lane(&net, "2", -1)).unwrap();
    assert!(entry.predecessors.is_empty());
    assert_eq!(entry.successors, [lane(&net, "99", -1)]);
    for od_id in [1, -1, -2] {
        let main = net.lane(lane(&net, "1", od_id)).unwrap();
        assert!(main.successors.is_empty() && main.predecessors.is_empty());
    }
}

#[test]
fn a_virtual_junction_keeps_where_its_roads_meet_the_main_road() {
    let (net, _) = load_file_with_provenance(FIXTURE).unwrap();
    let road = |id: &str| net.road_by_od_id(id).unwrap().id();
    let main = road("1");
    assert_eq!(
        net.virtual_junctions(),
        [VirtualJunction {
            od_id: "555".into(),
            name: "driveway".into(),
            main_road: main,
            s_start: 45.0,
            s_end: 75.0,
            orientation: Orientation::Positive,
            links: vec![
                VirtualLink {
                    from: LinkPoint::Along {
                        road: main,
                        s: 50.0,
                        forward: true,
                    },
                    to: LinkPoint::End {
                        road: road("2"),
                        end: RoadEnd::Start,
                    },
                    lanes: vec![(lane(&net, "1", -2), lane(&net, "2", -1))],
                },
                VirtualLink {
                    from: LinkPoint::End {
                        road: road("4"),
                        end: RoadEnd::End,
                    },
                    to: LinkPoint::Along {
                        road: main,
                        s: 50.0,
                        forward: true,
                    },
                    lanes: vec![(lane(&net, "4", -1), lane(&net, "1", -2))],
                },
                VirtualLink {
                    from: LinkPoint::Along {
                        road: main,
                        s: 90.0,
                        forward: false,
                    },
                    to: LinkPoint::End {
                        road: road("99"),
                        end: RoadEnd::End,
                    },
                    lanes: vec![(lane(&net, "1", 1), lane(&net, "99", 1))],
                },
            ],
        }]
    );
}

#[test]
fn only_a_link_naming_a_road_the_file_lacks_is_dropped() {
    let (_, prov) = load_file_with_provenance(FIXTURE).unwrap();
    assert_eq!(
        prov.warnings,
        [Warning::VirtualLinkDropped {
            junction_id: "555".into(),
            road_id: String::new(),
            connection_id: "3".into(),
        }]
    );
}

#[test]
fn a_virtual_junction_off_its_main_road_is_dropped() {
    let xml = std::fs::read_to_string(FIXTURE)
        .unwrap()
        .replace(r#"sEnd="75""#, r#"sEnd="175""#);
    let (net, prov) = load_str_with_provenance(&xml).unwrap();
    assert!(net.virtual_junctions().is_empty());
    assert!(prov.warnings.contains(&Warning::VirtualJunctionDropped {
        junction_id: "555".into()
    }));
}
