"""Write crg.xodr and the two OpenCRG files it names.

crg_bumps.crg is a 40 m by 7 m elevation grid at 0.2 m with a speed bump,
a washboard stretch, two potholes and a pair of ruts. crg_grip.crg is a
30 m by 7 m friction grid at 0.5 m with a wet patch. crg.xodr lays them on
four roads, one per mode:

- road 1, straight: crg_bumps.crg attached from s = 10, crg_grip.crg as
  friction from s = 45;
- road 2, a banked left arc: crg_bumps.crg attached, orientation opposite;
- road 3, straight: crg_bumps.crg genuine, starting at s = 10;
- road 4, straight: crg_bumps.crg global, placed by xOffset and yOffset.

Run from the repository root:

    python3 tests/data/crg.py
"""

import math
from pathlib import Path

HERE = Path(__file__).parent


def bumps(u, v):
    z = 0.0
    if 8.0 <= u <= 11.6:
        z += 0.07 * math.sin(math.pi * (u - 8.0) / 3.6)
    if 16.0 <= u <= 24.0:
        z += 0.01 * math.sin(2.0 * math.pi * (u - 16.0) / 0.8)
    for cu, cv, radius, depth in [(30.0, -1.5, 0.6, 0.05), (33.0, 1.8, 0.4, 0.03)]:
        r = math.hypot(u - cu, v - cv)
        if r < radius:
            z -= depth * 0.5 * (1.0 + math.cos(math.pi * r / radius))
    if u >= 26.0:
        for cv in (-0.9, 0.9):
            z -= 0.015 * math.exp(-(((v - cv) / 0.3) ** 2))
    return z


def grip(u, v):
    wet = 1.0
    wet *= 1.0 / (1.0 + math.exp(-(u - 10.0) * 2.0))
    wet *= 1.0 / (1.0 + math.exp((u - 20.0) * 2.0))
    wet *= 1.0 / (1.0 + math.exp(v * 3.0))
    return 0.9 - 0.5 * wet


def crg(path, comment, length, half, step, value):
    """An LRFI file: rows of 10-character values, 8 to a line."""
    columns = round(2 * half / step) + 1
    rows = round(length / step) + 1
    lines = [
        f"* {comment}",
        "* Generated by tests/data/crg.py.",
        "$ROAD_CRG",
        f"REFERENCE_LINE_INCREMENT = {step}",
        f"LONG_SECTION_V_RIGHT     = {-half}",
        f"LONG_SECTION_V_LEFT      = {half}",
        f"LONG_SECTION_V_INCREMENT = {step}",
        "$",
        "$KD_Definition",
        "#:LRFI",
    ]
    lines += [f"D:long section {c + 1},m" for c in range(columns)]
    lines += ["$", "$$$$"]
    for r in range(rows):
        values = [value(r * step, -half + c * step) for c in range(columns)]
        for at in range(0, columns, 8):
            lines.append("".join(f"{z:10.6f}" for z in values[at : at + 8]))
    path.write_text("\n".join(lines) + "\n")


def road(road_id, x, y, geometry, length, surface, profiles=""):
    lane = lambda i: (
        f'<lane id="{i}" type="driving"><width sOffset="0" a="3.5" b="0" c="0" d="0"/></lane>'
    )
    return f"""  <road id="{road_id}" length="{length}" junction="-1">
    <planView><geometry s="0" x="{x}" y="{y}" hdg="0" length="{length}">{geometry}</geometry></planView>
    {profiles}
    <lanes><laneSection s="0">
      <left>{lane(1)}</left><center><lane id="0" type="none"/></center><right>{lane(-1)}</right>
    </laneSection></lanes>
    <surface>
      {surface}
    </surface>
  </road>
"""


def main():
    crg(HERE / "crg_bumps.crg", "Bumps, washboard, potholes and ruts.", 40.0, 3.5, 0.2, bumps)
    crg(HERE / "crg_grip.crg", "Friction with a wet patch.", 30.0, 3.5, 0.5, grip)
    roads = [
        road(
            1, 0, 0, "<line/>", 80,
            '<CRG file="crg_bumps.crg" sStart="10" sEnd="50" orientation="same" mode="attached" sOffset="10"/>\n'
            '      <CRG file="crg_grip.crg" sStart="45" sEnd="75" orientation="same" mode="attached0" '
            'purpose="friction" sOffset="45"/>',
            '<elevationProfile><elevation s="0" a="0" b="0.02" c="0" d="0"/></elevationProfile>',
        ),
        road(
            2, 100, 0, '<arc curvature="0.0166667"/>', 60,
            '<CRG file="crg_bumps.crg" sStart="5" sEnd="45" orientation="opposite" mode="attached" sOffset="45"/>',
            '<lateralProfile><superelevation s="0" a="0.06" b="0" c="0" d="0"/></lateralProfile>',
        ),
        road(
            3, 0, -30, "<line/>", 60,
            '<CRG file="crg_bumps.crg" sStart="10" sEnd="50" mode="genuine" sOffset="10"/>',
        ),
        road(
            4, 0, -60, "<line/>", 60,
            '<CRG file="crg_bumps.crg" sStart="10" sEnd="50" mode="global" xOffset="10" yOffset="-60"/>',
        ),
    ]
    header = '<?xml version="1.0" encoding="UTF-8"?>\n<OpenDRIVE>\n  <header revMajor="1" revMinor="9"/>\n'
    (HERE / "crg.xodr").write_text(header + "".join(roads) + "</OpenDRIVE>\n")


if __name__ == "__main__":
    main()
